### PR TITLE
Primaryfix

### PR DESCRIPTION
**Pull request by brownd1978**
Fix MC primary particle for muon stops with full genealogy.   This includes fixes for Validation.  It requires updates to JobConfig as well.

### CODE REVIEW

**Comment by kutschke** [comment]
Off this thread Dave explained that this needed updates to fcl that were submitted to Production after this PR.  I will relaunch the CI to pick up the new fcl.

**Comment by kutschke** [comment]
@FNALbuild run build tests

**Comment by kutschke** [comment]
The issue with ceMix is "No Primary particle found" in event 2

**Comment by brownd1978** [comment]
Yes, the sample used for cemix is now out of date.   Tomorrow I’ll try to rework that so it can follow changes better.   

David Brown

**Comment by kutschke** [comment]
Will merge now because there is value in the nightly tests that we expect to run successfully,

**Pull request merged**
