### PR TITLE
Add BField files for DSMap_altDS11_helical

### PR DESCRIPTION
**Pull request by kutschke**
I added files for all maps and for the reco variant.  I am testing now with 2k events ceSimReco with standard and alt fields.

### CODE REVIEW

**Review by brownd1978 — CHANGES_REQUESTED** [review]
We use
"Offline/Mu2eG4/geom/bfgeom_no_tsu_ps_v01.txt"
when generating primaries from target stops, could you please provide the equivalent?

**Comment by kutschke** [comment]
> We use
> "Offline/Mu2eG4/geom/bfgeom_no_tsu_ps_v01.txt"
> when generating primaries from target stops, could you please provide the equivalent?

Done.

**Comment by kutschke** [comment]
I ran 1K ceSimReco using bfgeom_altDS11_helical_v01.txt .  Superficially it works OK.  The number of events in pRes plot was 84 before and 91 after.

**Comment by kutschke** [comment]
And Mu2eG4/geom/bfgeom_no_tsu_ps_altDS11_helical_v01.txt also passes a superficial test of 1K events of ceSimReco.

**Review by brownd1978 — APPROVED** [review]

**Pull request merged**
