### PR TITLE
Combinatorial Updater

### PR DESCRIPTION
**Pull request by brownd1978**
This PR introduces a combinatorial hit state assignment algorithm for the Mu2e KinKal fit.  It depends on a new release of KinKal, so is draft form until that's published.

### CODE REVIEW

**Comment by kutschke** [comment]
p026 is now present.  If you update .muse I can run the CI.

**Comment by brownd1978** [comment]
@FNALbuild run build test

**Comment by brownd1978** [comment]
@FNALbuild run build test

**Comment by kutschke** [comment]
@bonventre A gentle reminder that this PR is in your to-review list.  We are hoping to merge, tag, build and put on /cmvfs by EOB Fri July 1.

**Review by bonventre — APPROVED** [review]

**Comment by kutschke** [comment]
@FNALbuild run build test

**Pull request merged**
