### PR TITLE
Adding PDGCode labels to the TEveEventDisplay

### PR DESCRIPTION
**Pull request by sophiemiddleton**
Follow on from last weeks PR:

* Some code to fix recent SegFault
* Some work to add colour to the MCTrajectories (some work from @NamithaChitrazee here)
* Reverted 2D to tab structure in a bid to fix plotting bug (bug not fixed yet)

Still to do:
* Fix plotting feature in 2D plots for helix

### CODE REVIEW

**Comment by kutschke** [comment]
@FNALbuild run build tests

**Comment by kutschke** [comment]
Sophie: I see that you closed this.  If that was on purpose, please add a note to explain why.  If not, you can reopen it.

Thanks.

**Comment by sophiemiddleton** [comment]
Closed because I'm going to put in another PR which includes a fix to a 2D plotting bug and the correct coordinate system for the updated ROOT. Any previous new code is also included. Its on another branch so I couldnt just push to this PR.

**Comment by kutschke** [comment]
Thanks Sophie.  Once the new PR is in, please add comments in both PRs referencing each other.


From: Sophie Middleton ***@***.***>
Reply-To: Mu2e/Offline ***@***.***>
Date: Thursday, June 3, 2021 at 3:33 PM
To: Mu2e/Offline ***@***.***>
Cc: Rob Kutschke ***@***.***>, Team mention ***@***.***>
Subject: Re: [Mu2e/Offline] Adding PDGCode labels to the TEveEventDisplay (#466)


Closed because I'm going to put in another PR which includes a fix to a 2D plotting bug and the correct coordinate system for the updated ROOT. Any previous new code is also included. Its on another branch so I couldnt just push to this PR.

**Pull request closed without merging**
