### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by brownd1978**
Clarify KKFit parameter names.   Add print filtering by event/subrun.  Remove some time offsets.

### CODE REVIEW

**Comment by brownd1978** [comment]
@FNALbuild run build test with Mu2e/Production#239

**Review by rlcee — APPROVED** [review]
I wonder why the file name of Print/fcl/printCrvCoincidenceCluster.fcl is now disconnected from its content.

**Comment by brownd1978** [comment]
good catch, file restored.

**Comment by kutschke** [comment]
@bonventre A gentle reminder that this PR is on your list to review.

**Comment by kutschke** [comment]
@FNALbuild run build test

**Comment by brownd1978** [comment]
@FNALbuild run build test with Mu2e/Production#239

**Review by bonventre — APPROVED** [review]

**Comment by kutschke** [comment]
Merging this and Production 239 now.

**Pull request merged**
