### PR TITLE
Fixes for s132 (Don't include GeometryService in rootcling)

### PR DESCRIPTION
**Pull request by eflumerf**
Update CMakeLists.txt for new files.

Make it so check_cmake.sh can be run as `./bin/check_cmake.sh` (no copy to base directory)

### CODE REVIEW

**Comment by kutschke** [comment]
@eflumerf is the need to exclude the section of Surface steps drive by the new root in art 3.15 or is it driven by something intrinsic to cmake?  My own opinion is that data products should not use services but we have never been able to get agreement on that.

**Comment by eflumerf** [comment]
Basically, in s132, fhicl-cpp 4.19.00 includes c++20 code. ROOT cling does not understand c++20, so you cannot have a `#include "fhiclcpp/ParameterSet.h"` visible to any files which are processed by `rootcling` (i.e. included in a dictionary).

The change I made hides the GeometryService methods from `rootcling`, as they shouldn't be needed for object persistence in ROOT.

**Comment by eflumerf** [comment]
I think the result of this change to fhiclcpp is that you _cannot_ include services in data products until ROOT is updated to support c++20 in `rootcling`, which I think has an indefinite time-scale.

**Comment by kutschke** [comment]
> I think the result of this change to fhiclcpp is that you _cannot_ include services in data products until ROOT is updated to support c++20 in `rootcling`, which I think has an indefinite time-scale.

Thanks Eric.  I will approve and merge the PR and create an issue to discuss getting services out of data products, which I think is the preferred solution.

**Pull request merged**
