### PR TITLE
Delete Projects Package

### PR DESCRIPTION
**Pull request by AndrewEdmonds11**
The Projects package was only every a placeholder until something better came along. Muse is now here so we can delete this :)

### CODE REVIEW

**Comment by AndrewEdmonds11** [comment]
Hmm... I'm not sure why there are merge conflicts if I'm deleting files. I'll see if I can figure it out tomorrow

**Comment by kutschke** [comment]
I cloned your repo and looked at your PR branch.  I did:

git log --merges origin/delete-projects

The last merge on this branch is PR 335 from Feb 4.   So this is super far behind the head of master.  That's why the merge is complaining.

For what it's worth, here is what I do when I start a new project:

cd to my clone of my own Offline
git remote add -f mu2e https://github.com/Mu2e/Offline
git checkout -b mybranch mu2e/master
do my work
git push origin mybranch

So I always start new projects from the current head of mu2e/master.

If I already have the remote then I make sure it's up to date with:
checkout -b mu2emaster mu2e/master
git pull
git checkout -b mybranch mu2e/master

There is probably a way to clean this up and fetch mu2e/master but I get errors when I try what I think is the right command.

**Comment by AndrewEdmonds11** [comment]
Thanks, Rob. I see what I did now. I did:

```
git fetch mu2e master
git checkout --no-track -b delete-projects
```

when I should have done this:
```
git fetch mu2e master
git checkout --no-track -b delete-projects mu2e/master
```
Serves me right for trying to do things after 5pm. I will try again. Hopefully I can just change this PR without having to close it.

**Comment by kutschke** [comment]
Hi Andy,

  Yep.  I have done that before.

  If it turns out to be easier to close it and open a new one, just do it.  If you do, please add a comment explaining why you closed it.

Rob

From: Andrew Edmonds ***@***.***>
Reply-To: Mu2e/Offline ***@***.***>
Date: Wednesday, April 21, 2021 at 8:25 AM
To: Mu2e/Offline ***@***.***>
Cc: Rob Kutschke ***@***.***>, Team mention ***@***.***>
Subject: Re: [Mu2e/Offline] Delete Projects Package (#412)


Thanks, Rob. I see what I did now. I did:

git fetch mu2e master

git checkout --no-track -b delete-projects

when I should have done this:

git fetch mu2e master

git checkout --no-track -b delete-projects mu2e/master

Serves me right for trying to do things after 5pm. I will try again. Hopefully I can just change this PR without having to close it.

**Comment by AndrewEdmonds11** [comment]
run build tests

**Review by kutschke — APPROVED** [review]

**Pull request merged**
