### PR TITLE
Increase range of PBI

### PR DESCRIPTION
**Pull request by brownd1978**
Avoids sign bit overflow when NPOT > maxlong.  Backwards compatible with existing data.

### CODE REVIEW

**Review by kutschke — APPROVED** [review]
This looks straight forward.

**Comment by brownd1978** [comment]
tests succeeded.  ready to merge.

**Comment by kutschke** [comment]
@FNALbuild run build test

**Comment by kutschke** [comment]
I just relaunched the CI since it was out of date.  Will merge when it is done.



From: David Brown ***@***.***>
Reply-To: Mu2e/Offline ***@***.***>
Date: Wednesday, February 16, 2022 at 10:42 PM
To: Mu2e/Offline ***@***.***>
Cc: Rob Kutschke ***@***.***>, Assign ***@***.***>
Subject: Re: [Mu2e/Offline] Increase range of PBI (PR #712)


tests succeeded. ready to merge.

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Mu2e_Offline_pull_712-23issuecomment-2D1042570182&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=rTnPLpoCxTzdIlLl_y5INfuiTm4zq5WtJ4k25-wQtoqPprUQLFytMoGWP52B_P92&s=HU_-F2-c_0iphw1JqYzjsK18egDn4dhEXGD-OxJ0ilI&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABHY5ZT4OYV5OLLFRZLL4TLU3R4EPANCNFSM5OSRZM4A&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=rTnPLpoCxTzdIlLl_y5INfuiTm4zq5WtJ4k25-wQtoqPprUQLFytMoGWP52B_P92&s=VshmEU_UqTw_0tZcG5gFsJom9_1qiNMIM0_BVbNW1C0&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=rTnPLpoCxTzdIlLl_y5INfuiTm4zq5WtJ4k25-wQtoqPprUQLFytMoGWP52B_P92&s=KhNHuiNeKLkj1FFoyD4JxTP3fpxOH_i0bjNCvek5o28&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=rTnPLpoCxTzdIlLl_y5INfuiTm4zq5WtJ4k25-wQtoqPprUQLFytMoGWP52B_P92&s=jzfu8W8ZuzXqosSq4rFpwQGJy6lbWdnlnsJhN-p62mA&e=>.

**Pull request merged**
