### PR TITLE
Mu2e ii sm21

### PR DESCRIPTION
**Pull request by sophiemiddleton**
MU2EII_SM21: Initial Test of workflow - added instructions to the README.

### CODE REVIEW

**Comment by ryuwd** [comment]
Unrelated to the PR content, but something to keep in mind:

On triggering a build test, FNALbuild's default behaviour is to attempt to merge the PR into `master`, not `Mu2eII_SM21`, and run tests on the result of that. (conforming to the mu2e github workflow.) Since the PR base branch is not `master` the CI system as it is currently won't be able to properly validate these commits now, or in future PR's to `Mu2eII_SM21`.

**Comment by kutschke** [comment]
HI Ryun,

  The plan is that when people make a PR agains Mu2eII_SM21, they will need to do that by hand when they submit the PR.

  What would it take for the system to detect this and do the appropriate tests?  For now presume that the rules for running the tests are unchanged.


    Thanks,
                Rob

On Aug 7, 2020, at 9:51 AM, ryuwd <notifications@github.com<mailto:notifications@github.com>> wrote:



Unrelated to the PR content, but something to keep in mind:

On triggering a build test, FNALbuild's default behaviour is to attempt to merge the PR into master, not Mu2eII_SM21, and run tests on the result of that. (conforming to the mu2e github workflow.) Since the PR base branch is not master the CI system as it is currently won't be able to properly validate these commits now, or in future PR's to Mu2eII_SM21.

**Comment by ryuwd** [comment]
Hi Rob,

Perhaps moving the CI scripts (now in Mu2e/codetools in https://github.com/Mu2e/codetools/tree/master/bin/github/jenkins_tests) to a folder inside the Offline (say, Offline/CI) and maintaining them within the repository seems least complicated.

Then, the Jenkins jobs would run the CI scripts from the Offline clone rather than cloning Mu2e/codetools. CI workflows for their respective branches would then be maintained separately.

Best wishes, Ryun

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by kutschke** [comment]
Hi Ryun,


  What about keying off of the PR to figure out which branch to merge into?  Do you see how to do that part?

Rob


On Aug 7, 2020, at 10:29 AM, ryuwd <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Rob,

Perhaps moving the CI scripts (now in Mu2e/codetools in https://github.com/Mu2e/codetools/tree/master/bin/github/jenkins_tests<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Mu2e_codetools_tree_master_bin_github_jenkins-5Ftests&d=DwQFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=Jsp6Np0UiIGvDh5N6F1f9lYRV4fKEH1hooI70RM71_Y&s=5xKbt1RyivjLuxe492Crz-NiNWvgfTF62ZfNe0J5Oxk&e=>) to a folder inside the Offline (say, Offline/CI) and maintaining them within the repository seems least complicated.

Then, the Jenkins jobs would run the CI scripts from the Offline clone rather than cloning Mu2e/codetools. CI workflows for their respective branches would then be maintained separately.

Best wishes, Ryun

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ryuwd** [comment]
Hi Rob,

That part should be fine. I can get the merge target / base branch using the Github API, and pass that to Jenkins as a build parameter so the build tests are aware.

Best wishes, Ryun

**Comment by ryuwd** [comment]
As it turns out... I was overthinking things and the fix was a one-liner. see FNALbuild/cms-bot#24

Change will come into effect once Patrick merges.

**Comment by kutschke** [comment]
Thanks Ryun,

    How can I check that Patrick has done the merge?

    For now let’s leave the tests where they are.

Rob


On Aug 7, 2020, at 2:53 PM, ryuwd <notifications@github.com<mailto:notifications@github.com>> wrote:



As it turns out... I was overthinking things and the fix was a one-liner. see FNALbuild/cms-bot#24<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_FNALbuild_cms-2Dbot_pull_24&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=j2JRaGujsA8M3d79bEwR9BvnH9Rq6G6wfv--KDZNlsc&s=uvMsxfKrY_KubR_QiAv9wb0RftVjYOgCmOq7DsdiLqc&e=>

Change will come into effect once Patrick merges.

**Comment by ryuwd** [comment]
Hi Rob,

See the link in my last github comment- It links to PR #24 in the FNALbuild/cms-bot repo.

Best wishes, Ryun

**Comment by sophiemiddleton** [comment]
Hi, Are we awaiting a fix on the bot?

**Comment by ryuwd** [comment]
Hi Sophie, 

I think it'd be good to test the CI works before merging this

I'll try nudging Patrick to merge the bot changes

**Comment by kutschke** [comment]
Hi Ryun,

  He is on vacation.   I will check with his line management to learn who is backup is.

Rob

**Comment by sophiemiddleton** [comment]
Sure, let me know when its done. People are becoming aware of the branch, but given we dont expect any PR's for at least a few weeks, we can wait for the test to be done here. I'll make sure the instructions are seen by people.

**Comment by kutschke** [comment]
I just looked at the README.   If you follow these instructions exactly (with out remembering extra steps on your own), when you make the pull request, will it be directed at Mu2eII_SM21 or will it be directed at master.  Have you tested.

I strongly encourage people with write privs to this repo to follow a different developer workflow.  If you follow this workflow  then you are able to push directly from your clone to the branch in github.  You need to be able to do this for some special operations, such as adding tags to old commits.  But if you are doing "normal" work I recommend that you push to your own repo and make a PR.  Dave and I have a policy that we do not merge our own PRs, we ask the other one to do it.

I generally follow: https://mu2ewiki.fnal.gov/wiki/GitHubWorkflow#Developer_Workflow . Dave does something similar.  One feature is that we cannot accidentally push to the target branch in GitHub/Mu2e/Offline.  Another feature is that the master branch in our own repo is not part of the clone; it has no useful role in any workflow.

**Comment by ryuwd** [comment]
On reading the README myself, an important detail that has been left out is that any PR intended for `Mu2eII_SM21` must not be targeted at `master` when opening one from https://github.com/Mu2e/Offline/compare . The default action for any PR is that it targets `master` for the merge, especially if the work was done on the `Mu2eII_SM21` branch, and not on a feature branch...which can make this particular workflow prone to error (should be easy enough to spot though.)

Additionally, the README doesn't recommend the use of feature branches (as we use in the main workflow.)
Maybe this is worth considering?

**Comment by ryuwd** [comment]
So, to clarify (previous comment was a little jumbled, sorry) - something like

```
git clone <GitHub username>/Offline # clone your fork
git remote add mu2e https://github.com/Mu2e/Offline.git
git fetch mu2e
# create new feature branch off upstream (Mu2e/Offline) Mu2eII_SM21 branch
git checkout -b <my feature branch name> mu2e/Mu2eII_SM21

# do work and make commits as normal

# publish your feature branch
git push --set-upstream origin <my feature branch name>

```
then open a PR from your fork repo to `Mu2eII_SM21`

**Comment by ryuwd** [comment]
> Hi Ryun, He is on vacation. I will check with his line management to learn who is backup is. Rob 

Thanks for this!

**Comment by kutschke** [comment]
About Ryun's PR to CMSBOT.  Patrick is on vacation and he does not have a backup in this role since it is not officially supported.  At present SCD does not officially support any way to do testing from GitHub.

Ryun: can we flip the way we do things so that we run off of our repo that we periodically sync with what Patrick maintains? Or would it require development work by Patrick to allow this?  If it's possible now, is it something we could do ourselves, before Patrick is back?

**Comment by ryuwd** [comment]
Hi Rob,

Since this PR was prematurely merged we could revert this PR using the “revert” button at the bottom of the PR page.
Or we can open another to test the CI?

Best wishes, Ryun

**Comment by ryuwd** [comment]
Just a test
@FNALbuild run build test

**Comment by ryuwd** [comment]
I ran the tests with the new behaviour and CI does merge into the right branch (Mu2eII_SM21), and not master. 

To make it clearer in future what exactly is happening during a merge, I added extra information to the "results" table showing what commit was merged, and at what point exactly it was merged. It should show up in CI tests soon.

**Pull request merged**
