### PR TITLE
(CI Test) Test new permissions system

### PR DESCRIPTION
**Pull request by ryuwd**

### CODE REVIEW

**Comment by ryuwd** [comment]
Teams aren't being mentioned properly, that has now been fixed 

```
@Write, @mu2eii_sm21_ci have access to CI actions on Mu2eII_SM21.
```
should have been
```
@Mu2e/write, @Mu2e/mu2eii_sm21_ci 
```

**Comment by ryuwd** [comment]
@FNALbuild test

I shouldn't be able to trigger tests because I am not in @Mu2e/mu2eii_sm21_ci or @Mu2e/write.

**Comment by ryuwd** [comment]
OK, everything looks good.

**Comment by kutschke** [comment]
Do you need anything more from me?

On 9/16/20, 11:42 AM, "ryuwd" <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #247<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Mu2e_Offline_pull_247&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=a_ysA2kjiXrvi-liVPBTp3zkWNw2fY2iHwVfrYtY3bQ&s=cuLHqr2Fm_kfP6b8RDFks5g_5q9abXRtX6iGi5aqVo0&e=>.

**Comment by ryuwd** [comment]
Thanks! Everything should be set up now.

**Comment by ryuwd** [comment]
@FNALbuild test

**Pull request closed without merging**
