### PR TITLE
setting DeltaFinder as the new default for Compton-hits flagging

### PR DESCRIPTION
**Pull request by gianipez**

### CODE REVIEW

**Comment by gianipez** [comment]
This PR has to be merged with:
- https://github.com/Mu2e/mu2e_trig_config/pull/46
- https://github.com/Mu2e/Production/pull/374

**Comment by gianipez** [comment]
@FNALbuild run build test with https://github.com/Mu2e/Production/pull/374 https://github.com/Mu2e/mu2e_trig_config/pull/46

**Comment by gianipez** [comment]
@FNALbuild run build test with https://github.com/Mu2e/Production/pull/374 and https://github.com/Mu2e/mu2e_trig_config/pull/46

**Comment by gianipez** [comment]
@FNALbuild run build test with https://github.com/Mu2e/Production/pull/374

**Review by brownd1978 — APPROVED** [review]

**Pull request merged**
