### PR TITLE
removed duplicate hits in Crv coincidence clusters

### PR DESCRIPTION
**Pull request by ehrlich-uva**

### CODE REVIEW

**Comment by ehrlich-uva** [comment]
Not ready. Please don't merge.

**Comment by ehrlich-uva** [comment]
Now the PR is ready for merging.

**Comment by kutschke** [comment]
@FNALbuild run build test

**Review by kutschke — APPROVED** [review]
I don't think that we have anyone who can review this properly.  I will approve and merge.  We can look at the nightly validation output tomorrow AM.

**Pull request merged**
