### PR TITLE
Added functionality to filter on CrvSteps

### PR DESCRIPTION
**Pull request by oksuzian**

### CODE REVIEW

**Comment by kutschke** [comment]
@AndrewEdmonds11 and @oksuzian   Are tihs PR and #1108 independent of each other or do they need to be considered together?

**Comment by oksuzian** [comment]
> @AndrewEdmonds11 and @oksuzian Are tihs PR and #1108 independent of each other or do they need to be considered together?

They are independent.

**Review by brownd1978 — APPROVED** [review]
Looks good.

**Comment by brownd1978** [comment]
@FNALbuild run build test

**Pull request merged**
