### PR TITLE
Stereo hit making sequence updates

### PR DESCRIPTION
**Pull request by brownd1978**
These mods make stereo hit making part of the default reco sequence.  Additional scripts are provided to adjust the sequence for testing.

### CODE REVIEW

**Comment by brownd1978** [comment]
@FNALbuild run build test

**Comment by kutschke** [comment]
@myucel-fnal a gentle reminder this PR is on your to-review list.

**Comment by myucel-fnal** [comment]
In the latest commit, comments and names are inconsistent. For example:
In TrkHitReco/fcl/epilog_FBH_plane.fcl,
#
#  Post-prolog switch to output station-level ComboHits from FlagBkgHits
#
physics.producers.FlagBkgHits.OutputLevel : "plane"

Commented out line refers to wrong output level. Same is true for epolog_FBH_station.fcl.

Otherwise I don't see any real issues so far.

**Review by myucel-fnal — CHANGES_REQUESTED** [review]
Please fix commented lines referring to wrong output level in epilog_FBH_plane and epolog_FBH_station.fcl.

**Review by myucel-fnal — APPROVED** [review]

**Comment by kutschke** [comment]
@FNALbuild run build test

**Comment by kutschke** [comment]
@FNALbuild run build test

**Pull request merged**
