### PR TITLE
reduce CRV default printing

### PR DESCRIPTION
**Pull request by rlcee**
per #640

### CODE REVIEW

**Review by kutschke — APPROVED** [review]
Looks good.  I will merge shortly

**Comment by kutschke** [comment]
@ehrlich-uva Ralf: a head's up on this PR.  Ray has reduced the default level of printout for some of your code.  I support the plan make the default for most informational printout to default to off - real warnings and errors should default to on.  I plan to merge this at 2:00 PM today, Fermilab time.  If you have any objections please get back to me by then.  If you agree with the changes, please let me know and I will merge earlier.

**Comment by ehrlich-uva** [comment]
Hi Rob, I have no objections. You can merge this PR.

**Comment by kutschke** [comment]
@FNALbuild run build test

**Comment by kutschke** [comment]
> Hi Rob, I have no objections. You can merge this PR.

Thanks - I will update the tests and merge.

**Pull request merged**
