### PR TITLE
Deliberate error in order to see how CMS-BOT behaves with an error.

### PR DESCRIPTION
**Pull request by kutschke**
This pull request has a deliberate error in GeneralUtilities/src/RMS.cc so that I can see how the CMS-BOT system responds to an error.

### CODE REVIEW

**Comment by kutschke** [comment]
@FNALbuild run code checks

**Comment by kutschke** [comment]
@FNALbuild run build test

**Comment by kutschke** [comment]
I am closing this now.  Let's see if it remains in the list of closed issues.

**Comment by ryuwd** [comment]
@FNALbuild run code checks

**Comment by ryuwd** [comment]
OK - I think I know what happened. 

The bot ignored the request because of a problem with github comment timestamps / time lag.
If you send a command/comment too close to when the bot sends its last comment, it might get ignored due to the time lag, since it uses the timestamps that github records, not its own database.

**Comment by ryuwd** [comment]
Test - please ignore

@FNALbuild run code checks

**Comment by ryuwd** [comment]
test - please ignore
check FNALbuild does the appropriate thing when I mention a command to it that doesn't make sense/match any of the test triggers

@FNALbuild wash the dishes

**Comment by ryuwd** [comment]
Added in a feature recently to print which files threw build errors - triggering a build from Jenkins to test.

**Comment by ryuwd** [comment]
@FNALbuild run code checks

Test messages with new regex configuration.

**Comment by ryuwd** [comment]
Code/whitespace checks now working

**Comment by ryuwd** [comment]
Clang tidy and clang-format now working nicely.

**Comment by ryuwd** [comment]
Try to cut down verbose output...

**Comment by ryuwd** [comment]
second row of table should have :x: mark, not :heavy_check_mark: - fixed now!

**Pull request closed without merging**
