### PR TITLE
clean up constants

### PR DESCRIPTION
**Pull request by rlcee**
- put constants in global constants
- finishes #235
- validated to point of using values

### CODE REVIEW

**Comment by kutschke** [comment]
@bonventre I added you as a reviewer since you were the last person to touch the part of the code that Ray changed.  So this mostly an FYI.  I suspect you may not be the main author of those lines but that history is lost.

**Comment by rlcee** [comment]
The Issue this addresses was created by Andrei, so he should probably sign off.

**Comment by kutschke** [comment]
@gaponenko This started as a request from you so I am adding you as a reviewer.

**Comment by kutschke** [comment]
Hi Ray,

  Thanks for the heads up.  I have added him as a reviewer.  He is on vacation today and will be back tormoww.  Is is Ok for you if this is not approved until his return?

  I have a meeting with Kyle at 10:30.
  Rob



From: Ray Culbertson ***@***.***>
Reply-To: Mu2e/Offline ***@***.***>
Date: Tuesday, September 27, 2022 at 9:35 AM
To: Mu2e/Offline ***@***.***>
Cc: Rob Kutschke ***@***.***>, Assign ***@***.***>
Subject: Re: [Mu2e/Offline] clean up constants (PR #857)


The Issue this addresses was created by Andrei, so he should probably sign off.

**Comment by kutschke** [comment]
@gaponenko a gentle reminder that this PR is in your input queue.

**Review by kutschke — APPROVED** [review]

**Comment by kutschke** [comment]
Unless I hear otherwise, I plan to merge this PR this evening.  If either of the reviewers wants more time, please let me know.

**Comment by kutschke** [comment]
@FNALbuild run build test

**Comment by rlcee** [comment]
> Hello, this PR as is does not address the "wrong for non-aluminum targets" part of the issue.

It looks like this overlaps exactly with the default physics values in Issue #484.  If you reply to my comment on that with how you would like to see partial material info handled, then the fix here will follow suit.

**Comment by gaponenko** [comment]
Thank you, Ray.  I commented on #484

**Comment by rlcee** [comment]
I attached the RMC values to Al target material. All access will throw with a meaningful message if a requested value was not explicitly loaded from the config file. (#484)

**Review by bonventre — APPROVED** [review]

**Comment by kutschke** [comment]
@FNALbuild run build test

**Comment by kutschke** [comment]
@FNALbuild run build test

**Pull request merged**
