### PR TITLE
fixPbarWindowAndWedgeAtTS3

### PR DESCRIPTION
**Pull request by rhbob**
Sorting through, all with Hayman 2. TS_03 with the TS_03 window/6-strip wedge = 1533+-4 (.001533 stopped muons/pot, all errors ~+-4).  Next TS_03 with 3-strip wedge instead, 1583 which makes sense since that has less wedge material in the muon region.  Then TS_05 is 1428 which is low because the window is enormously thick, should never be used.  TS_06 is the A1100 version (all above are Be or Kapton) and gives 1542, which is lower than 1583 because it reflects a "buildable" wedge that just has more material. All these yields make sense relative to each other and relative to the old Tier 1 target. So 1542+-4 is the yield.

### CODE REVIEW

**Comment by kutschke** [comment]
@FNALbuild run build test

**Comment by rlcee** [comment]
Recall that we have now 

geom_common ->Mu2eG4/geom/geom_common_hayman_v2.txt
(most defaults)
geom_common_current ->Mu2eG4/geom/geom_2019_PhaseI_hayman_v2.txt
(bleeding edge)

- You have commented on changing TS_05 to TS_06, but updating your hayman file will change users from TS_03 to TS_06, what do you expect for that?

- common_current contains TS_05, so your comments would apply to that file, but where is the top-level file that updates that?

**Comment by rhbob** [comment]
Hi,

I see, I got mixed up between the versions floating around, my fault.

I'm looking at the files right now. I want the default to be that geom_common = geom_common_current_hayman_v2.txt be TS_06 and it isn't.  I also want geom_common_current to be TS_06. Anything else ought not to be used any more.

Since I'm looking at the files right now I can see they don't do that. I want to make geom_common and geom_common_current use TS_06.  So I will need to do that and resubmit the pull request. What's the right procedure for that?

Do you want to know what happens in going from TS_v03 + Hayman 2 to TS_v06 + Hayman 2?  I only know the former is 1508+-30, not small enough errors.  I can run that tomorrow.  Let me fix the defaults, run the two configs, and do whatever I need for another pull.  Do you just reject the one I submitted?

--thanks, Bob


Robert Bernstein
Fermi National Accelerator Laboratory

Mu2e Co-Spokesperson
Snowmass 2021 Rare Process Co-Convener
Chair, Wilson Fellow Committee
Visiting Scholar, Cornell University Dept of Human Development
office: (630) 840-2035
cell:    (708) 846-1782
rhbob@fnal.gov<mailto:rhbob@fnal.gov>















On Mar 24, 2020, at 8:22 PM, Mar 24, 2020, Ray Culbertson <notifications@github.com<mailto:notifications@github.com>> wrote:



Recall that we have now

geom_common ->Mu2eG4/geom/geom_common_hayman_v2.txt
(most defaults)
geom_common_current ->Mu2eG4/geom/geom_2019_PhaseI_hayman_v2.txt
(bleeding edge)

  *   You have commented on changing TS_05 to TS_06, but updating your hayman file will change users from TS_03 to TS_06, what do you expect for that?

  *   common_current contains TS_05, so your comments would apply to that file, but where is the top-level file that updates that?

**Comment by rlcee** [comment]
Also recall that we agreed to never change the files which contain the top-level
includes.  Files like geom_common_current_hayman_v2.txt should not change, new top-level files
should be added with the changes.  Then change geom_common and geom_common_current to point to the new top-level files.  Since we have two heads (default=common and bleeding edge= common_ciurrent) then you will need two new top-level files.  (I couldn't be sure if these ideas were implicit in the previous discussion, or not).

**Comment by rhbob** [comment]
this is where I'm getting messed up.

I can't get to /mu2e/app/ right now which is maybe a good thing.

According to you, I think (hesitate, is this right?)

geom_common_current_hayman_v2.txt

should be unchanged and I add geom_common_current_hayman_v3.txt and that will have the TS_v06 version, is that right?

then

geom_common_current ->Mu2eG4/geom/geom_2019_PhaseI_hayman_v2.txt

should become geom_2019_Phase1_hayman_v3.txt with my window/wedge changes.

But look at this:


Also recall that we agreed to never change the files which contain the top-level
includes. Files like geom_common_current_hayman_v2.txt should not change, new top-level files
should be added with the changes. Then change geom_common and geom_common_current to point to the new top-level files. Since we have two heads (default=common and bleeding edge= common_ciurrent) then you will need two new top-level files. (I couldn't be sure if these ideas were implicit in the previous discussion, or not).

This seems to contradict what Rob said:

My suggestion is that you just delete Mu2eG4/geom/geom_common_hayman_v2_TS06.txt . You need to both git rm and git commit.

Then make new file which differs from Mu2eG4/geom/geom_2019_PhaseI_hayman_v2.txt by one line, the #include'd TransportSolenoid file. Add and commit it. Then push.

the first line is a problem: delete the file seems to break things and contradict what Ray said.

--Bob

Robert Bernstein
Fermi National Accelerator Laboratory

Mu2e Co-Spokesperson
Snowmass 2021 Rare Process Co-Convener
Chair, Wilson Fellow Committee
Visiting Scholar, Cornell University Dept of Human Development
office: (630) 840-2035
cell:    (708) 846-1782
rhbob@fnal.gov<mailto:rhbob@fnal.gov>















On Mar 25, 2020, at 9:27 AM, Mar 25, 2020, Ray Culbertson <notifications@github.com<mailto:notifications@github.com>> wrote:



Also recall that we agreed to never change the files which contain the top-level
includes. Files like geom_common_current_hayman_v2.txt should not change, new top-level files
should be added with the changes. Then change geom_common and geom_common_current to point to the new top-level files. Since we have two heads (default=common and bleeding edge= common_ciurrent) then you will need two new top-level files. (I couldn't be sure if these ideas were implicit in the previous discussion, or not).

**Comment by kutschke** [comment]
> On Mar 25, 2020, at 9:46 AM, rhbob <notifications@github.com> wrote:
> 
> 
> this is where I'm getting messed up. 
> 
> I can't get to /mu2e/app/ right now which is maybe a good thing. 

The final sync to the new hardware is underway.  I thought it would available but readonly
during this time.  In any case you can't write to it.

I will get to the rest of this a little later


> According to you, I think (hesitate, is this right?) 
> 
> geom_common_current_hayman_v2.txt 
> 
> should be unchanged and I add geom_common_current_hayman_v3.txt and that will have the TS_v06 version, is that right? 
> 
> then 
> 
> geom_common_current ->Mu2eG4/geom/geom_2019_PhaseI_hayman_v2.txt 
> 
> should become geom_2019_Phase1_hayman_v3.txt with my window/wedge changes. 
> 
> But look at this: 
> 
> 
> Also recall that we agreed to never change the files which contain the top-level 
> includes. Files like geom_common_current_hayman_v2.txt should not change, new top-level files 
> should be added with the changes. Then change geom_common and geom_common_current to point to the new top-level files. Since we have two heads (default=common and bleeding edge= common_ciurrent) then you will need two new top-level files. (I couldn't be sure if these ideas were implicit in the previous discussion, or not). 
> 
> This seems to contradict what Rob said: 
> 
> My suggestion is that you just delete Mu2eG4/geom/geom_common_hayman_v2_TS06.txt . You need to both git rm and git commit. 
> 
> Then make new file which differs from Mu2eG4/geom/geom_2019_PhaseI_hayman_v2.txt by one line, the #include'd TransportSolenoid file. Add and commit it. Then push. 
> 
> the first line is a problem: delete the file seems to break things and contradict what Ray said. 
> 
> --Bob 
> 
> Robert Bernstein 
> Fermi National Accelerator Laboratory 
> 
> Mu2e Co-Spokesperson 
> Snowmass 2021 Rare Process Co-Convener 
> Chair, Wilson Fellow Committee 
> Visiting Scholar, Cornell University Dept of Human Development 
> office: (630) 840-2035 
> cell: (708) 846-1782 
> rhbob@fnal.gov<mailto:rhbob@fnal.gov%3E 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
>

**Comment by michaelmackenzie** [comment]
Hi Bob,

Is there a reason that geom_common_hayman_v2_TS06.txt only includes the updates done to the TS and backs out the updates done to the rest of the model for the MARS and CRY campaigns? Is there a geometry config file you intend to be used that includes all of the updates? Or should we just update the geom_2019_PhaseI_hayman_v2.txt to include TS06?

Best,
Michael

Comparison:
$ diff -b Mu2eG4/geom/geom_common_hayman_v2_TS06.txt Mu2eG4/geom/geom_2019_PhaseI_hayman_v2.txt 

< #include "Mu2eG4/geom/mu2eHall_v02.txt"
---
> #include "Mu2eG4/geom/mu2eHall_v03.txt"
41,42c42,43
< #include "Mu2eG4/geom/DetectorSolenoid_v03.txt"
< #include "Mu2eG4/geom/DSShielding_v01.txt"
---
> #include "Mu2eG4/geom/DetectorSolenoid_v04.txt"
> #include "Mu2eG4/geom/DSShielding_v02.txt"
47c48
-------- Here's the expected change--------------------------
< #include "Mu2eG4/geom/TransportSolenoid_v06.txt" 
---
> #include "Mu2eG4/geom/TransportSolenoid_v05.txt"
50,51c51,52
-------------------------------------------------------------------------
< #include "Mu2eG4/geom/ExtShieldUpstream_v05.txt"
< #include "Mu2eG4/geom/ExtShieldDownstream_v05.txt"
---
> #include "Mu2eG4/geom/ExtShieldUpstream_v06.txt"
> #include "Mu2eG4/geom/ExtShieldDownstream_v06.txt"
53c54
< #include "Mu2eG4/geom/Pipe_v03.txt"
---
> #include "Mu2eG4/geom/Pipe_v04.txt"
61c62
< #include "Mu2eG4/geom/muonBeamStop_v05.txt"
---
> #include "Mu2eG4/geom/muonBeamStop_v07.txt"
150a152,153

**Comment by rhbob** [comment]
Hi Michael,

(Ray, Rob, Dave, you probably get this anyway)

So what I did was check out the head and make my changes to _05 and call it _06.  Otherwise I didn't do anything.  When I checked it out it was what I wrote before:

JobConfig/common/geom_baseline.txt

which calls

Mu2eG4/geom/geom_common.txt"


which calls

#include "Mu2eG4/geom/geom_common_hayman_v2.txt"

which calls

#include "Mu2eG4/geom/TransportSolenoid_v06.txt"

for JobConfig/validation/singleStageStoppedMuons.fcl.

One of the issues is that it seems validation runs a different sequence that doesn't use _Phase1_.  I don't know what should be used.  All I know is that the little snippet I changed to go to _05 to _06 works and the above sequence gives yields that I've cross-checked a bunch of different ways.

I shouldn't be making decisions about what the standard geometry file is, but I think there ought to be precisely one I think.  I have to say having _Phase1_ in a non-standard naming convention seems like a trip hazard to me but I am the least competent person in this discussion to have an opinion on this.

FWIW, I would like us to settle on a convention.  George is telling me he wants a different window now and we need a more robust scheme.

--thanks, Bob


Robert Bernstein
Fermi National Accelerator Laboratory

Mu2e Co-Spokesperson
Snowmass 2021 Rare Process Co-Convener
Chair, Wilson Fellow Committee
Visiting Scholar, Cornell University Dept of Human Development
office: (630) 840-2035
cell:    (708) 846-1782
rhbob@fnal.gov<mailto:rhbob@fnal.gov>

On Apr 8, 2020, at 12:52 PM, Apr 8, 2020, michaelmackenzie <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi Bob,

Is there a reason that geom_common_hayman_v2_TS06.txt only includes the updates done to the TS and backs out the updates done to the rest of the model for the MARS and CRY campaigns? Is there a geometry config file you intend to be used that includes all of the updates? Or should we just update the geom_2019_PhaseI_hayman_v2.txt to include TS06?

Best,
Michael

Comparison:
$ diff -b Mu2eG4/geom/geom_common_hayman_v2_TS06.txt Mu2eG4/geom/geom_2019_PhaseI_hayman_v2.txt

< #include "Mu2eG4/geom/mu2eHall_v02.txt"

#include "Mu2eG4/geom/mu2eHall_v03.txt"
41,42c42,43
< #include "Mu2eG4/geom/DetectorSolenoid_v03.txt"
< #include "Mu2eG4/geom/DSShielding_v01.txt"

________________________________

#include "Mu2eG4/geom/DetectorSolenoid_v04.txt"
#include "Mu2eG4/geom/DSShielding_v02.txt"
47c48
-------- Here's the expected change--------------------------
< #include "Mu2eG4/geom/TransportSolenoid_v06.txt"

________________________________

#include "Mu2eG4/geom/TransportSolenoid_v05.txt"
50,51c51,52

________________________________
< #include "Mu2eG4/geom/ExtShieldUpstream_v05.txt"
< #include "Mu2eG4/geom/ExtShieldDownstream_v05.txt"

#include "Mu2eG4/geom/ExtShieldUpstream_v06.txt"
#include "Mu2eG4/geom/ExtShieldDownstream_v06.txt"
53c54
< #include "Mu2eG4/geom/Pipe_v03.txt"

________________________________

#include "Mu2eG4/geom/Pipe_v04.txt"
61c62
< #include "Mu2eG4/geom/muonBeamStop_v05.txt"

________________________________

#include "Mu2eG4/geom/muonBeamStop_v07.txt"
150a152,153

**Comment by michaelmackenzie** [comment]
Hi Bob,

That makes sense. I think in that case we should update Phase I and Phase II  geometry files to point to TS06. I think geom_common.txt was using TS03 at the time, rather than TS05 which is why I asked. The Phase I and Phase II were introduced as we currently expect the geometry to be different for the run before and after the shutdown (right now it's just a change to specialty shielding). I agree the naming convention should be more set soon. 

Personally, I think we can just have a Phase I and II file that gets updated in git, rather than creating new versions, and a few versions hanging around if multiple geometry setups are supposed to be simultaneously supported. I think having geom_common.txt point to a stable geometry and geom_common_current.txt point to the latest and greatest geometry would also make sense (so maybe a common and current for each phase?).

Best,
Michael

**Comment by michaelmackenzie** [comment]
Hi All,

I'm currently going through this update, and incorporating Bob's update to the pbar wedge to use a different material. This update doesn't change geom_common.txt, do we want to keep this unchanged and have it use the geometry prior to the MARS and CRY updates but with the updated production target as it is now?

I'm going to update geom_common_current.txt to use the updated pbar window/wedge, including the titanium window Bob has implemented. I'm also changing the updated TransportSolenoid_v06/v07.txt files to include the previous version and then change the necessary component to make the difference between the versions more transparent.

Let me know if this sounds sensible and I can finish up these edits. Perhaps the reorganization of the top level files can come in an update after this, so these changes can be captured in the geometry updates currently being implemented.

Best,
Michael

**Comment by kutschke** [comment]
@FNALbuild run build test

**Pull request merged**
