### PR TITLE
new envset for scons v4_2_0

### PR DESCRIPTION
**Pull request by macndev**
new envset p013 to pick up new scons version v4_2_0 is the only change

### CODE REVIEW

**Comment by rlcee** [comment]
Symptoms seem like maybe this test ran before the envset was visible on cvmfs.  So I'd just try to build again after verifying the envset is there..

**Comment by rlcee** [comment]
@FNALbuild run build test
The envset is visible

**Review by kutschke — APPROVED** [review]
This is ready to go.  

I will merge it on Monday - just in case there are issues let's do it during business hours.

**Comment by kutschke** [comment]
Test comment to see if I need to retest.

**Comment by kutschke** [comment]
@FNALbuild run build test

**Pull request merged**
