### PR TITLE
create a compressed PDG code

### PR DESCRIPTION
**Pull request by rlcee**
- move compressPdgId from General to Mu2e utilities since it depends on DataProducts
- update the two modules which were using it
- add a PDG ID compression to 27 bins
- add a function to create a histogram for the compressed ID

### CODE REVIEW

**Comment by kutschke** [comment]
@rlcee  is this ready to rerun the CI?

**Comment by kutschke** [comment]
@FNALbuild run build test

**Comment by kutschke** [comment]
@FNALbuild run build test

**Comment by kutschke** [comment]
When I first submitted the CI request, GitHub told me that I could not comment because GitHub was overloaded.  So I waited a few minutes and made a second comment requesting the CI.  it looks to me like both comments actually worked.

**Comment by rlcee** [comment]
@FNALbuild run build test

**Pull request merged**
