### PR TITLE
Updates from the pbar2m group

### PR DESCRIPTION
**Pull request by gianipez**
- fixed the configuration of the TTtimeClusterFinder module instance
- updates to the DeltaFinder module; now it counts and flags the proton tracks
- updates to McTrackUtils
- updates to the LsqSum2 class; now it provides also the fit error on the "slope"

### CODE REVIEW

**Comment by gianipez** [comment]
The fix in the `TTtimeClusterFinder` module instance is expected to bump up the TPR trigger efficiency by ~10%. This should be visible in the nightly validation jobs.

**Comment by brownd1978** [comment]
@FNALbuild run build test

**Comment by brownd1978** [comment]
@FNALbuild run build test

**Comment by brownd1978** [comment]
@FNALbuild run build test

**Comment by brownd1978** [comment]
@FNALbuild run build test

**Comment by gianipez** [comment]
@FNALbuild run build test

**Comment by rlcee** [comment]
@FNALbuild run build test

**Comment by brownd1978** [comment]
@FNALbuild run build test

**Comment by rlcee** [comment]
@FNALbuild run build test
one more check that the system is working again (jenkins was restarted0

**Pull request merged**
