### PR TITLE
introduced namespaces in: TrkPatRec, CosmicReco, CaloMC, CaloCluster, CaloReco, TrkHitReco prolog files

### PR DESCRIPTION
**Pull request by gianipez**

### CODE REVIEW

**Comment by gianipez** [comment]
This PR goes together with https://github.com/Mu2e/Production/pull/324 

tagging: @kutschke , @rlcee , @brownd1978

**Comment by gianipez** [comment]
Now we have an additional dependence on https://github.com/Mu2e/mu2e_trig_config/pull/31

**Review by brownd1978 — APPROVED** [review]

**Comment by kutschke** [comment]
@FNALbuild run build test with Mu2e/Production#324

**Comment by kutschke** [comment]
The final CI was done after merging mu2e_trig_config PR 31.

**Pull request merged**
