### PR TITLE
removal of the prolog_trigger files and clean up of the Trigger package

### PR DESCRIPTION
**Pull request by gianipez**
- removed the prolog_trigger fcl files moved to the mu2e_trig_repo
- refactoring of the Trigger/ package

### CODE REVIEW

**Comment by gianipez** [comment]
@FNALbuild run build test

**Comment by gianipez** [comment]
@FNALbuild run build test

**Review by brownd1978 — CHANGES_REQUESTED** [review]
The changes here are purely subtractive, removing the trigger config from Offline.   Before this PR can be merged you need to add the replacement configuration that allows the trigger to be invoked in the Offline environment.  That includes providing the replacement for building the trigger paths (was done in the python target), the replacement #include of those paths in Production ([here](https://github.com/Mu2e/Production/blob/24af79374ecc75034801c904926f70c6b6d117af/JobConfig/digitize/prolog.fcl#L11)), and an expansion of MU2E_SEARCH_PATH so that it can find the prolog_trigger.fcl files in the new repo.  This PR will also need to be processed with a tag or PR of that repo and Production in order to pass the CI.

**Comment by rlcee** [comment]
>  MU2E_SEARCH_PATH 

I think it is FHICL_FILE_PATH needed here

**Comment by kutschke** [comment]
@FNALbuild run build test with Mu2e/Production#288

**Comment by rlcee** [comment]
the CI fail because it does not have mu2e_trig_config yet.  Is the decision to include this repo in parallel with Offline and Production final?  If so, I can add it to CI and validation

**Comment by rlcee** [comment]
> the CI fail because it does not have mu2e_trig_config yet. Is the decision to include this repo in parallel with Offline and Production final? If so, I can add it to CI and validation

Also I'm not sure if that repo is fully operational yet

**Comment by gianipez** [comment]
Hello @rlcee , 

I edited the SConscript in the mu2e_trig_config repo so that it generates the trigger menu files. The fcl files in Offline/Trigger/fcl were already edited accordingly.

**Comment by rlcee** [comment]
> Hello @rlcee ,
> 
> I edited the SConscript in the mu2e_trig_config repo so that it generates the trigger menu files. The fcl files in Offline/Trigger/fcl were already edited accordingly.

I'm getting errors like
chmod: cannot access ���build/sl7-prof-e28-p055/mu2e_trig_config/gen/trig_physMenu_OnSpill.fcl���: No such file or directory
during both the "running SConscripts" stage and the build stage.  generally in the scons pattern, no files should be created during the SConscripts stage.  Why do you need to chmod the files?  In the Offline version, the files come up 644.

**Comment by kutschke** [comment]
There are two things that we need to work on.

@rlcee We have made the decision that the standard set of repos is Offline, Product, mu2e_trig_config.  Please update CI and nightly for this.

@gianipez  I have a test area with all 3 repos built.  The 4 jobs that failed above, still fail in my test area.  The reason is that hte string "Offline/Trigger/fcl/prolog_trigger.fcl" still appears in both Offline and Production.   Please add new commits to both of your PRs to fix this.

**Comment by kutschke** [comment]
> Also I'm not sure if that repo is fully operational yet

I found that Offline and Production are not yet fully edited.  Are there other issues that you are aware of?  If so, please let Giani know so that he can address them before I merge.

**Comment by rlcee** [comment]
> > Also I'm not sure if that repo is fully operational yet
> 
> I found that Offline and Production are not yet fully edited. Are there other issues that you are aware of? If so, please let Giani know so that he can address them before I merge.

I standby to update CI.   Above, I noted chmod and structure build issues.  If you are not seeing these issues, I'd be interested in how you are running.

**Comment by kutschke** [comment]
@brownd1978  Did you and Giani discuss the following during the design phase?

There are circular includes.   Offline has includes from mu2e_trig_config and mu2e_trig_config has includes from Offline.  I think that the dependencies should be a tree (ie no loops).

**Comment by kutschke** [comment]
> I standby to update CI. Above, I noted chmod and structure build issues. If you are not seeing these issues, I'd be interested in how you are running.

Yes.  I see these too. I had to grep the log file to find them since they don't return errors.   These must be cleaned up before we merge.

Giani: there is a lot of homework for you. Let me know if you have any questions.

**Comment by gianipez** [comment]
I updated all the repos following the comments received. 
Regarding the question of the `#include "mu2e_trig_config/..."` includes in the Offline I think that we can safely generate the fcl files left in `Trigger/fcl` in the `mu2e_trig_config` repo at build time. The other test files using the mu2e_trig_config in Mu2eKinKal/test are not part of the Validation suite, so to me it doesn't seem a big deal to keep them in the Offline, but I'll let @brownd1978 voice his opinion on that.

**Comment by kutschke** [comment]
> I updated all the repos following the comments received. Regarding the question of the `#include "mu2e_trig_config/..."` includes in the Offline I think that we can safely generate the fcl files left in `Trigger/fcl` in the `mu2e_trig_config` repo at build time. The other test files using the mu2e_trig_config in Mu2eKinKal/test are not part of the Validation suite, so to me it doesn't seem a big deal to keep them in the Offline, but I'll let @brownd1978 voice his opinion on that.

Thanks Giani.  I will look at the code tomorrow.  Dependency loops are always dangerous and I think it's important to resolve this before we merge this PR.

**Comment by rlcee** [comment]
Giani has cleanup up the scons function in mu2e-trig_config, so I'm Ok with adding it to CI now.  I'll wait until tomorrow morning, in case someone wants to add anything.  It should run OK without this PR since it will just build the new fcl disconnected from the existing fcl.

**Comment by rlcee** [comment]
@FNALbuild run build test with Mu2e/Production/#288

**Comment by rlcee** [comment]
```
  File "/scratch/workspace/GitHubPRTests/mu2e-offline-build-test/mu2e_trig_config/python/generateMenuFromJSON.py", line 314, in generate
    generateMenu(args.evtMode, args.outdir, dict_agg_triggers, 'agg_'+tag, data_streams, add_proc_name, False, True, args.verbose, False, True, args.verbose)
TypeError: generateMenu() takes from 7 to 9 positional arguments but 12 were given

```
result of adding mu2e_trig_config to CI, not sure what's happening

**Comment by rlcee** [comment]
cut-n-paste error n line 314 of generateMenuFromJSON.py
@gianipez please update and we can try again

**Comment by gianipez** [comment]
Hi @rlcee , I found an extra cut&paste made by mistake. I just pushed the commit to fix the code.

**Comment by rlcee** [comment]
@FNALbuild run build test with Mu2e/Production#288

**Comment by rlcee** [comment]
I've added mu2e_trig_config to the nightly validation too, so it will start getting built.  It is not clear if, after these PR's are merged, it will be run in validation, the answer lies in reviewing Production/Validation/nightly/*.  I expect it will mostly be used.  We will need to add it to the muse published CI (what you get with "muse setup HEAD") and musings, when they come about.  Probably some other places I can't think of right now, but will reveal themselves.

**Comment by rlcee** [comment]
Some observations:
1) last night the validation saw these errors, I thought these were removed, but it seems they have returned
chmod: cannot access '/exp/mu2e/app/users/rlc/dev/build/sl7-prof-e28-p055/mu2e_trig_config/gen/trig_physMenu_OnSpill.fcl': No such file or directory
2) there is probably a way to avoid chmod in cmake too, that would be a nice improvement
3) the python run failed, but did not report a fail to scons, so maintaining return codes would be another thing to look at
4) it looks like you have avoided using PR's in mu2e_trig_config repo, I think we need to do that, since this will be critical infrastructure

**Comment by kutschke** [comment]
@gianipez What is your plan for addressing the remaining run time failures in the CI?  The last CI test did included the PR to Production; and mu2e_trig_config was included in that test.

Also there are still loops in the repo dependencies between Offline and mu2e_trig_config.   The places in which Offline includes from mu2e_trig_config are:

```
Mu2eKinKal/test/TTBTrk.fcl
Mu2eKinKal/test/TTTA_noMC.fcl
Mu2eKinKal/test/TTTA.fcl
```

Since these are all tests we can discuss an exception to the no loops rule, as we have for Offline including from Production.

Whatever the resolution I would like it to document it.

**Comment by brownd1978** [comment]
What are we waiting on for this PR?  Can someone provide a checklist in this thread?

**Comment by gianipez** [comment]
Hello @brownd1978 , apologies for the delay. I finalizing some changes needed in the Production repository.

**Comment by gianipez** [comment]
Hi there,
I just pushed the necessary changes in `Production` and `mu2e_trig_config`. 
Regarding the files in `Mu2eKinKal/test`, I leave the decision to @brownd1978 . Probably, they can be moved in a separate analysis repo I guess.

**Comment by gianipez** [comment]
@FNALbuild run build test with https://github.com/Mu2e/Production/pull/288

**Comment by gianipez** [comment]
@FNALbuild run build test with https://github.com/Mu2e/Production/pull/288

**Comment by kutschke** [comment]
Rerun CI because of intervening merges:

@FNALbuild run build test with Mu2e/Production#288

**Comment by gianipez** [comment]
@FNALbuild run build test with https://github.com/Mu2e/Production/pull/288

**Comment by kutschke** [comment]
@gianipez I think that the issue is in Jenkins.  I have asked Ray to look into it.

**Comment by kutschke** [comment]
> @gianipez I think that the issue is in Jenkins. I have asked Ray to look into it.

I take that back.  I can reproduce interactively.  The issue is in mu2e_trig_config.  It is also blocking Sophie's PR.  Please look into it.

**Comment by kutschke** [comment]
More information.  The last successful CI run was at 9:25 AM today .  I see that you made 4 commits to mu2e_trig_config .  It looks like you are pushing directly to the GitHub repo - is that right?  The time stamps on the commits are when you committed in your local clone.  So I don't know when any of these were pushed to GitHub.

Given that the text of the error message says "cosmic_main", in my working ara I rolled back to 8ce9f7ff87 ( added paths to the OffSpill mode) . That builds successfully.

**Comment by gianipez** [comment]
@FNALbuild run build test with https://github.com/Mu2e/Production/pull/288

**Comment by kutschke** [comment]
@FNALbuild run build test with Mu2e/Production#288

**Comment by kutschke** [comment]
@brownd1978 Giani tells me that he considers this PR and Production 288 complete.  When you have a chance, please have a look.  Once you are satisfied, please approve both this and production 288.

**Review by brownd1978 — APPROVED** [review]

**Review by brownd1978 — APPROVED** [review]

**Pull request merged**
