### PR TITLE
Jcdoc

### PR DESCRIPTION
**Pull request by brownd1978**
Add documentation on Simulation workflow.  Rename a few files for consistency.

### CODE REVIEW

**Review by kutschke — COMMENTED** [review]
Great figures.  This is really good.  Is there a master document in preparation that uses these figures?

What's the difference between these two files:
JobConfig/doc/SimulationWorkflow.dot
JobConfig/doc/SimulationWorkflow.dot.dot

Is this file a leftover:
JobConfig/doc/file 

In JobConfig/doc/,  are all of the graphics format files just different format images of the same source?

Maybe a READme.md to say some of the above?

**Review by kutschke — COMMENTED** [review]
The file JobConfig/mixing/mix.fcl that you renamed is still referenced in 2 places:
./JobConfig/mixing/Run1.fcl
./JobConfig/mixing/NoPrimary.fcl

**Review by kutschke — COMMENTED** [review]
The file that you renamed: JobConfig/reco/reco.fcl 

Is still referenced in 5 places
./JobConfig/reco/IPA-Michel.fcl
./JobConfig/reco/NoPrimary-mix.fcl
./TrkDiag/fcl/TrkAnaDigisReco.fcl
./Validation/fcl/reco.fcl

**Comment by brownd1978** [comment]
Thanks for catching the name-change follow-on.  I removed all the spurious graphics files from /doc, only the .pdf was supposed to be there, the rest were the residue of testing.  I added a README.

**Comment by kutschke** [comment]
Thanks.  I see you also caught the follow-on JobConfig/reco/CeEndpoint.fcl which I missed-moused into my earlier comment.

I will rerun tests and merge.

**Comment by kutschke** [comment]
@FNALbulid run build tests

**Pull request merged**
