### PR TITLE
test of workflow

### PR DESCRIPTION
**Pull request by sophiemiddleton**
MU2EII_SM21: Testing merge workflow for @ryuwd

### CODE REVIEW

**Comment by ryuwd** [comment]
@FNALbuild run build test

**Comment by ryuwd** [comment]
@FNALbuild run build test

**Comment by ryuwd** [comment]
@FNALbuild run build test

**Comment by ryuwd** [comment]
Found an unrelated bug caused when trying to trigger the bot by email reply. Unicode characters in the email reply / comment, when printed to logs for debugging output, would fail to be decoded and throw an exception. I submitted a fix

**Comment by sophiemiddleton** [comment]
let me know if you want me to close the request at all

**Comment by ryuwd** [comment]
Everything looks good. Thanks!

**Comment by kutschke** [comment]
@FNALbuild run build tests

**Pull request merged**
