### PR TITLE
small fixes to compile with cmake

### PR DESCRIPTION
**Pull request by gianipez**

### CODE REVIEW

**Review by eflumerf — APPROVED** [review]
Looks good to me, FWIW

**Comment by kutschke** [comment]
@gianipez I see that you have been adding commits.  Please let me know when you are finished and I will merge it.

**Comment by kutschke** [comment]
@eflumerf Do you need a new tag after this merge?  If so, what should it be, d11_02_01?

**Comment by eflumerf** [comment]
I've asked Giani if he'll want a new tag; if he does he will have to update the CMakeLists.txt version so that the UPS product is generated with the right version number

**Comment by gianipez** [comment]
Thanks for asking, Eric. I don't think we need a new tag. 
I'm done with the commits, @kutschke , so feel free to merge at your convenience.

**Comment by kutschke** [comment]
There is no coverage in the CI so I am not rerunning the CI.  Merging now.

**Pull request merged**
