### PR TITLE
Update to doc888 v13 geometry

### PR DESCRIPTION
**Pull request by brownd1978**
I created a new pattern for this PR to make sure it is distinct from older datasets.

### CODE REVIEW

**Comment by kutschke** [comment]
Richie: please check the changes to TrackerMaker.cc .  I understand the changes to the other two filles.

**Review by bonventre — APPROVED** [review]

**Comment by bonventre** [comment]
There is a docdb-888v14 now that this is also in agreement with (I think that version just added more clarifying text)

**Comment by brownd1978** [comment]
@FNALbuild run build test

**Comment by brownd1978** [comment]
I added some fixes to this PR not directly related to geometry but necessary to testing, please have a look at just the last commit.

**Review by rlcee — APPROVED** [review]

**Comment by brownd1978** [comment]
@FNALbuild run build test

**Pull request merged**
