### PR TITLE
extract common code

### PR DESCRIPTION
**Pull request by rlcee**

### CODE REVIEW

**Comment by kutschke** [comment]
Is this designed to be merged after #842 ?  Or can they be merged in either order?

**Comment by rlcee** [comment]
> Is this designed to be merged after #842 ? Or can they be merged in either order?

Let's do this one second.  It might conflict..

**Comment by kutschke** [comment]
@FNALbuild run build test

**Review by kutschke — APPROVED** [review]

**Comment by kutschke** [comment]
@rlc  I merged your earlier PR, which created the expected conflicts in this one.  I wil redo the CI and merge as soon as you push the fix.   You may also be able to resolve it using the GitHub web editor.

**Comment by kutschke** [comment]
@FNALbuild run build test

**Comment by kutschke** [comment]
Need to redo CI for changes merged in Production.

@FNALbuild run build test

**Pull request merged**
