### PR TITLE
start STMWaveforms

### PR DESCRIPTION
**Pull request by rlcee**
Print and val routines for new STM product

### CODE REVIEW

**Review by AndrewEdmonds11 — APPROVED** [review]
Ray pointed me to an example Validation file and Print output. It looks great to me

**Comment by kutschke** [comment]
No idea why CI did not run.  Doing it now.

@FNALbuild run build test

**Comment by kutschke** [comment]
... I also see that the first buildbot message that announces the proposed changes did not run until after my recent comment

**Comment by kutschke** [comment]
Helenka says that the problem with the CI not running appears to be glitch on the GitHub side.  Let's watch to see if it repeats on other PRs.

**Pull request merged**
