### PR TITLE
Extmon geom

### PR DESCRIPTION
**Pull request by gaponenko**
This pull requests adds ExtMonDetectorRoom volume in geometry.  It does not correspond to anything physical, but is a "mother volume" to contain ExtMon detector and supports, and reduce the number of items in the HallAir volume.  I also renamed a not very descriptive "extMon" into "extMonExteriorWall", improved error handling, and committed some cleanups.  This PR should not change any physics results, but G4 random numbers in validation may become different.

### CODE REVIEW

**Comment by kutschke** [comment]
Andrei: can you suggest one or two reviewers for this PR?

**Comment by gaponenko** [comment]
On Wed, 9 Dec 2020, Rob Kutschke wrote:

> Andrei: can you suggest one or two reviewers for this PR?  

Michael MacKenzie.  I do not know who else is experienced with the 
geom/bldg/*.ccl files, and one of the commits touches them.

Andrei

**Review by dnbrow01 — APPROVED** [review]
This comment is about the first of the five commits on this branch...
This looks like a fairly routine (though Extensive) set of whitespace changes, including:
- Extra space/tab at end of line
- Wrong indentation for comments
- Wrong indentation on line continuations (some question in my mind of what are the right indentation guidelines here, but not critical)
- Removed extra indentation on continuation after an equal sign (I would not have made these, but no harm in choosing this style).
No change in performance of code from this commit.  Thank you to Andrei for this considerable effort.

**Review by dnbrow01 — APPROVED** [review]
This commit (the second in this PR) removes an old, already deprecated mechanism for the building of the coll2Shielding as a box, and the implementation of building a set of virtual detectors.  This is useful cleanup and I don't see problems.

**Review by dnbrow01 — APPROVED** [review]
Third commit of PR (maybe I shouldn't being breaking this down by commit?) introduces the ExtMonDetectorRoom.  My main concern would have been for overlaps, but that is checked in test suite, I think?  The code itself looks good.

**Review by dnbrow01 — COMMENTED** [review]
Fourth commit - parameter renaming.  Nothing suspicious here.

**Review by dnbrow01 — APPROVED** [review]
Fixes a problem with not handling exceptions (triggered by changes in other commits, I'm sure).  This is useful protection and is a good addition to the code.  Thanks, Andrei.

**Comment by dnbrow01** [comment]
I am happy with the changes in this pull request.  Added code is minimal and conforms to good practices.  Mostly cleanup of old/deprecated code, a valuable service.

**Comment by gaponenko** [comment]
Hi Dave,

On Wed, 9 Dec 2020, Dave Brown wrote:

> @dnbrow01 approved this pull request.

>  Third commit of PR (maybe I shouldn't being breaking this down by
> commit?) 

For this PR the commits (except whitespace) are independent, so it's
the same amount of reviewing no matter how you do it.  I've reviewed
some requiests where later commits undo things introduced by earlier
commits, for those cases using the "files changed" tab and collapsing
commits made more sense.

By the way,  you can attach a comment to a specific code line in github.


> introduces the ExtMonDetectorRoom.  My main concern would
> have been for overlaps, but that is checked in test suite, I think?

I also ran the overlap check.  The 0.1 mm detectorRoomMargin was intoduced to
pass that.

Andrei

**Comment by gaponenko** [comment]
On Wed, 9 Dec 2020, Dave Brown wrote:

> @dnbrow01 commented on this pull request.
> 
> Fourth commit - parameter renaming.  Nothing suspicious here.

That's the one I wanted to be checked by an expert the most.  I hope I
updated the naming everywhere consistently, and did not miss
something.

Andrei

**Comment by dnbrow01** [comment]
Yes, it appeared complete to me - both old and new txt files and each instance of the old name appeared to have a change associated.

Best Regards,
Dave B(Lou)

> On Dec 9, 2020, at 5:26 PM, Andrei Gaponenko <notifications@github.com> wrote:
> 
> CAUTION: This email originated from outside of our organization. Do not click links, open attachments, or respond unless you recognize the sender's email address and know the contents are safe.
> 
> 
> On Wed, 9 Dec 2020, Dave Brown wrote:
> 
> > @dnbrow01 commented on this pull request.
> > 
> > Fourth commit - parameter renaming. Nothing suspicious here.
> 
> That's the one I wanted to be checked by an expert the most. I hope I
> updated the naming everywhere consistently, and did not miss
> something.
> 
> Andrei
> 
> > 
> > 
> > 
> > -- 
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub:
> > https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Mu2e_Offline_pull_284-23pullrequestreview-2D548645753&d=DwICaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=O47fc5vzDTR2V_gla4Ub0Q&m=hJ3FgKMp7gnuUeEx7Baxqfb9m96VmNLuos_EeRp8-NY&s=FBBE5gBKsYrrbNwP-ru0rtqC0cdPpGs-VCT62DsWAQY&e=
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

******************************************
David N. Brown, Ph.D.
Associate Dean for Graduate Education
College of Arts & Sciences
Professor of Physics
Brown Fellows Mentor, Class of 2023
Faculty Senator
University of Louisville
Louisville, KY 40292  USA
david.brown@louisville.edu
he/him/his
******************************************

**Comment by kutschke** [comment]
@FNALbuild run build tests

**Pull request merged**
