### PR TITLE
Changes needed for mu2e_artdaq_core v1_06_02 compatibility

### PR DESCRIPTION
**Pull request by eflumerf**

### CODE REVIEW

**Comment by kutschke** [comment]
Hi Eric,

  If  I merge this in to the head of master and do not change any UPS products will it work?  Or will it only work with the new UPS products that you gave to Mackenzie.

Rob

From: eflumerf ***@***.***>
Reply-To: Mu2e/Offline ***@***.***>
Date: Tuesday, July 13, 2021 at 10:57 AM
To: Mu2e/Offline ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Mu2e/Offline] Changes needed for mu2e_artdaq_core v1_06_02 compatibility (#527)

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/Mu2e/Offline/pull/527<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Mu2e_Offline_pull_527&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=Kmevgp2tcTPXNvrLmtLO7dDINNhSB7ZiV34Z1WiVj3M&s=lz4sCro18vffqvNZ5AfUeSgXK-1XbMrgXzraaZz0K18&e=>

Commit Summary
·         updated script using MUSE vars
·         clean up + updated ups-maker script
·         Merge branch 'v10_00_00_ots' of github.com:gianipez/Offline into v10_00_00_ots
·         Start work on supporting Mu2eEventFragment
·         More Mu2eEventFragment compatibility
·         More updates to the DAQ modules, get them building
·         small fixes
·         fixed env variables
·         Merge branch 'master' into v10_01_00_ots
·         Merge branch 'master' into v10_01_00_ots
·         Fix a few header accesses
File Changes
·         M DAQ/inc/CaloDAQUtilities.hh<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Mu2e_Offline_pull_527_files-23diff-2D1937a0a01a876b01e3d695375ee9036848e55896cec16798af2e5de7d81df20b&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=Kmevgp2tcTPXNvrLmtLO7dDINNhSB7ZiV34Z1WiVj3M&s=FJmEj7nqh6Dmt1gcFW7LUCtGFxRQNTa9QlIpkj6oCvM&e=> (14)
·         M DAQ/src/CaloDAQUtilities.cc<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Mu2e_Offline_pull_527_files-23diff-2Dd35f314f796d2ef4fe7751b6a5ec9d6a69df66d799288c1ba65e9a5e2ce31c10&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=Kmevgp2tcTPXNvrLmtLO7dDINNhSB7ZiV34Z1WiVj3M&s=G9Lv8Y4GdvetKumniszkvVa5DVROs9eZJUu5GjLA3Og&e=> (27)
·         M DAQ/src/CaloHitsFromFragments_module.cc<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Mu2e_Offline_pull_527_files-23diff-2D4292cb895952670db63397e4a8c17b5b6f9ff9eed0b9c65ccf898ab73cc07dd5&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=Kmevgp2tcTPXNvrLmtLO7dDINNhSB7ZiV34Z1WiVj3M&s=Szr1caS8HX9q4aImyn6qPwAvDK_tjahVQ2RZy1bEy-E&e=> (164)
·         M DAQ/src/CaloRecoFromFragments_module.cc<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Mu2e_Offline_pull_527_files-23diff-2D69813e2541b13c67298221b07148d6f7b5797df945c9f32bafad643c2abd8635&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=Kmevgp2tcTPXNvrLmtLO7dDINNhSB7ZiV34Z1WiVj3M&s=aFjcClBGhmRdYZ5DnTc2EVxHO7AyUxqzP5rxjAEhFKE&e=> (162)
·         M DAQ/src/CrvDigisFromFragments_module.cc<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Mu2e_Offline_pull_527_files-23diff-2Dbcc0e67b05427c2afa71c52a8f25539026d754ce02c3c3429eb248ac2a178177&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=Kmevgp2tcTPXNvrLmtLO7dDINNhSB7ZiV34Z1WiVj3M&s=zPBPAmna6oqHQTuGPhk86bVJcfGZEoGuQ0-MK1QIlr0&e=> (20)
·         M DAQ/src/FragmentAna_module.cc<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Mu2e_Offline_pull_527_files-23diff-2D648c7b003f7b73747f5147d5947528b2dd823a5ee072dc6a678c058dabd61daa&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=Kmevgp2tcTPXNvrLmtLO7dDINNhSB7ZiV34Z1WiVj3M&s=2RpuM7JbwH1BbtRXmytVPn6asJFoXbWTRqsd3f4jBiA&e=> (121)
·         M DAQ/src/PrefetchDAQData_module.cc<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Mu2e_Offline_pull_527_files-23diff-2D14232e7fa86e09e1c8f60a51823a43901b4d5322e5c7d2e74a054723bd9d89a0&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=Kmevgp2tcTPXNvrLmtLO7dDINNhSB7ZiV34Z1WiVj3M&s=TGxkewv2t0jp4opNVrwDw2Yx2ZWldh-2bJH9yKk6Fg8&e=> (13)
·         M DAQ/src/StrawAndCaloDigisFromFragments_module.cc<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Mu2e_Offline_pull_527_files-23diff-2D7eb9d9bed9e4bb76b3d1fde2a8b4b0f73325c9137a1c630650a0fac87316a6ed&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=Kmevgp2tcTPXNvrLmtLO7dDINNhSB7ZiV34Z1WiVj3M&s=ZwfwzJWunFuDektgtAqPOl0PD4YVxB4kT4WUae76Dr4&e=> (201)
·         M DAQ/src/StrawHitRecoFromFragments_module.cc<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Mu2e_Offline_pull_527_files-23diff-2D524183e439c01af17acbd566fddb7e9774f891d9eb31a6726501d5fdf63f0acc&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=Kmevgp2tcTPXNvrLmtLO7dDINNhSB7ZiV34Z1WiVj3M&s=nPXFdmzalHG7nzH5dyAwGbY-iCQHKIKa4RnNxX8tqQc&e=> (14)
·         M DAQ/src/StrawRecoFromFragments_module.cc<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Mu2e_Offline_pull_527_files-23diff-2D37ffbc844b579db89ddfdf38a99c865719949c55fbb69c598ddbc00316866ac2&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=Kmevgp2tcTPXNvrLmtLO7dDINNhSB7ZiV34Z1WiVj3M&s=GZN1tVYmzIBzJ6Nh16bnPSWVLcwDozeF-KfB89Qo2Ww&e=> (76)
·         M Trigger/fcl/prolog_trigger.fcl<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Mu2e_Offline_pull_527_files-23diff-2Defba21e0faa5f9f04b3dfcd0dfd7d1191cc33c291c8a32ce2cf4fe8e92bb352c&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=Kmevgp2tcTPXNvrLmtLO7dDINNhSB7ZiV34Z1WiVj3M&s=nlrXOd4MUemzE2ZNWrOyCtjc6un7VEjs1cYCWyCZfNE&e=> (10)
·         M ups_install/install.sh<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Mu2e_Offline_pull_527_files-23diff-2D5b6e166ce68e503a0da16dfcbc07786a6a4b86a6f290f668d762c9882fcab05c&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=Kmevgp2tcTPXNvrLmtLO7dDINNhSB7ZiV34Z1WiVj3M&s=Z3VWQnnU31LV5Pl0DEy7fVYe71Z7bmfs33mV-jbLerc&e=> (22)
·         M ups_install/installTableFile.sh<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Mu2e_Offline_pull_527_files-23diff-2Dfb346890b6d097c8297282c6d85da8992d124d245f06c1221c9de7f15c47957c&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=Kmevgp2tcTPXNvrLmtLO7dDINNhSB7ZiV34Z1WiVj3M&s=pPS3tFTi8VZjqwQF9317q5ZkRExvcR_u3Y3adT3CvPE&e=> (24)
Patch Links:
·         https://github.com/Mu2e/Offline/pull/527.patch<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Mu2e_Offline_pull_527.patch&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=Kmevgp2tcTPXNvrLmtLO7dDINNhSB7ZiV34Z1WiVj3M&s=SMWsSzEMw01L84QsnULCABJpW44zsvRjyHS1Re-IcD8&e=>
·         https://github.com/Mu2e/Offline/pull/527.diff<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Mu2e_Offline_pull_527.diff&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=Kmevgp2tcTPXNvrLmtLO7dDINNhSB7ZiV34Z1WiVj3M&s=GZAR_c5nJ02khrrT16m0_aTckog6fYqoqMY2zKmQvnA&e=>

**Comment by eflumerf** [comment]
It will only work with mu2e_artdaq_core v1_06_02 and pcie_linux_kernel_module v2_05_06. The API in pcie_linux_kernel_module has changed, from `DTC_DataHeaderPacket& GetHeader()` to `std::shared_ptr<DTC_DataHeaderPacket> GetHeader()`. This is actually one of the key changes that enabled the much faster trigger processing that Giani reported on at the collab. meeting.

**Comment by kutschke** [comment]
Hi Eric,

  Then it’s not what I asked for.  Makenzie’s job is to test a new version of art and it’s dependent products.  It’s important to isolate that from other changes.

  Please deliver the UPS products that I asked for,

Rob


From: eflumerf ***@***.***>
Reply-To: Mu2e/Offline ***@***.***>
Date: Tuesday, July 13, 2021 at 11:03 AM
To: Mu2e/Offline ***@***.***>
Cc: Rob Kutschke ***@***.***>, Team mention ***@***.***>
Subject: Re: [Mu2e/Offline] Changes needed for mu2e_artdaq_core v1_06_02 compatibility (#527)


It will only work with mu2e_artdaq_core v1_06_02 and pcie_linux_kernel_module v2_05_06. The API in pcie_linux_kernel_module has changed, from DTC_DataHeaderPacket& GetHeader() to std::shared_ptr<DTC_DataHeaderPacket> GetHeader(). This is actually one of the key changes that enabled the much faster trigger processing that Giani reported on at the collab. meeting.

**Comment by kutschke** [comment]
The build failed because this PR requires a new version of the TDAQ ups products.  These, in turn, require a new version of art.  I have asked Eric to provide the UPS products that we need to test this version of Offline.

**Comment by eflumerf** [comment]
The TDAQ UPS products do *not* require new art, they work perfectly find with s109. Given that art is still having problems, I think it might be a good idea to get the Offline updated to use the new pcie_linux_kernel_module API to make this whole process a lot easier when s112 comes around...

**Comment by kutschke** [comment]
Hi Eric,

  Yes.  That’s a good idea.  I can reopen your PR.

   As I understand it we still need to update some UPS products – right?  Are the correct ones already installed in /cvmfs?  If not, what does Mackenzie need to install.

     Rob


From: eflumerf ***@***.***>
Reply-To: Mu2e/Offline ***@***.***>
Date: Thursday, July 15, 2021 at 11:16 AM
To: Mu2e/Offline ***@***.***>
Cc: Rob Kutschke ***@***.***>, Assign ***@***.***>
Subject: Re: [Mu2e/Offline] Changes needed for mu2e_artdaq_core v1_06_02 compatibility (#527)


The TDAQ UPS products do not require new art, they work perfectly find with s109. Given that art is still having problems, I think it might be a good idea to get the Offline updated to use the new pcie_linux_kernel_module API to make this whole process a lot easier when s112 comes around...

**Comment by eflumerf** [comment]
It looks like pcie_linux_kernel_module v2_05_06 and mu2e_artdaq_core v1_06_02 simply need to have s109 builds done. Kyle may not have made a s109 build of artdaq_core v3_07_02 when he released it, I can provide that.

**Comment by kutschke** [comment]
Thanks Eric,

  Please provide the artdaq_core build.

  Mackenzie: please bulid and install the s109 builds of the UPS products that Eric requested.

Thanks,

Rob


From: eflumerf ***@***.***>
Reply-To: Mu2e/Offline ***@***.***>
Date: Thursday, July 15, 2021 at 11:56 AM
To: Mu2e/Offline ***@***.***>
Cc: Rob Kutschke ***@***.***>, Assign ***@***.***>
Subject: Re: [Mu2e/Offline] Changes needed for mu2e_artdaq_core v1_06_02 compatibility (#527)


It looks like pcie_linux_kernel_module v2_05_06 and mu2e_artdaq_core v1_06_02 simply need to have s109 builds done. Kyle may not have made a s109 build of artdaq_core v3_07_02 when he released it, I can provide that.

**Comment by kutschke** [comment]
Because the release of the next art is now delayed, I am reopening this PR.  We will test once the necessary UPS products are  in place.

**Comment by macndev** [comment]
Hi, I have been installing the necessary s109 products that were mentioned earlier, I just got to installing MADC and a dependency popped up that was not listed in this thread. The s109 version of MADC v1_06_02 seems to be dependent on the s109 version of pcie v2_05_03. I am building the other pcie now, but I wanted to share the dependency in case it is a surprise.

**Comment by kutschke** [comment]
Eric: any comments?

From: macndev ***@***.***>
Reply-To: Mu2e/Offline ***@***.***>
Date: Thursday, July 15, 2021 at 2:00 PM
To: Mu2e/Offline ***@***.***>
Cc: Rob Kutschke ***@***.***>, State change ***@***.***>
Subject: Re: [Mu2e/Offline] Changes needed for mu2e_artdaq_core v1_06_02 compatibility (#527)


 the necessary s109 products that were mentioned earlier, I just got to installing MADC and a dependency popped up that was not listed in this thread. The s109 version of MADC v1_06_02 seems to be dependent on the s109 version of pcie v2_05_03. I am building the other pcie now, but I wanted to share the dependency in case it is a surprise.

—

**Comment by eflumerf** [comment]
This is my fault. I said MADC v1_06_02, when the correct version is v1_06_03! (It should depend on pcie v2_05_06 and artdaq_core v3_07_02)

**Comment by macndev** [comment]
Got it, thanks!

**Comment by kutschke** [comment]
@FNALbuild run build tests

**Comment by kutschke** [comment]
Eric:  the errors in the build are all of the form:
Offline/DAQ/src/CaloRecoFromFragments_module.cc:19:10: fatal error: CaloConditions/inc/CaloDAQMap.hh: No such file or directory
   19 | #include "CaloConditions/inc/CaloDAQMap.hh"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

You cloned your base before Ray added the Offline/ prefix to all include directives to include files from Offline.  Please go through your PR and add these in. 

Thanks.

**Comment by eflumerf** [comment]
@FNALbuild run build tests

**Comment by kutschke** [comment]
Eric: one more thing.  Presuming this builds and passes tests.  Who are sensible reviewers?  Anyone except Giani who is on vacation?

**Comment by eflumerf** [comment]
Apart from Giani, I think @bonventre might be a decent person to look at it, I think he's been into this code before...

**Comment by kutschke** [comment]
The issue with the build is the same as last time: the prefix Offline/ on the include paths.  I guess my last email crossed paths with your launch of the CI build.

**Comment by eflumerf** [comment]
I just merged `master` in, as my initial grepping didn't see any more after that...I've gone through with a finer comb and found a few more.

**Comment by kutschke** [comment]
Let’s see what the CI finds this time.  

The merge is not guaranteed to find everything.  For example, if you added a new include, it won’t fix that.

**Comment by kutschke** [comment]
@FNALbuild run build tests

**Comment by bonventre** [comment]
It looks like you still need to change StrawHitRecoFromFragments_module.cc to use the new method of getting the TrackerFragments.

Also reading through everything there's some duplication of code between Giani and I that we need to clean up but we can work that out in the next PR when he's back.

**Comment by eflumerf** [comment]
> 
> 
> It looks like you still need to change StrawHitRecoFromFragments_module.cc to use the new method of getting the TrackerFragments.
> 
> Also reading through everything there's some duplication of code between Giani and I that we need to clean up but we can work that out in the next PR when he's back.

I've updated StrawHitRecoFromFragments, copying code from StrawRecoFromFragments and ensuring that it builds.

**Review by bonventre — APPROVED** [review]

**Comment by kutschke** [comment]
@FNALbuild run build tests

**Pull request merged**
