### PR TITLE
Add normalization printout to generator tool

### PR DESCRIPTION
**Pull request by brownd1978**
This is an intermediate PR, progressing towards adding normalization metadata to generator outputs to facilitate downstream analysis. This current PR just prints the relevant information to cout. Subsequent PRs need to design a class that covers this and other generators. Refactoring of BinnedSpectrum may ultimately be needed. The current change results in this printout (for example) running DIOtail:

Restricted Spectrum min 75.005 max 104.965
Full Spectrum min 1.005 max 104.965
Restricted Spectrum integral 4.15143e-05
Full Spectrum integral 99.1255
Sampled spectrum fraction 4.18805e-07

### CODE REVIEW

**Review by kutschke — APPROVED** [review]

**Review by sophiemiddleton — APPROVED** [review]
looks good to me

**Comment by kutschke** [comment]
@rlcee   and   @oksuzian : a gentle reminder that this PR is on your list to review.

**Review by rlcee — APPROVED** [review]
I'm approving assuming these questions have answers
- why not do the integral in the BinnedSpectrum class
- what is the adjustment of the first bin in the full integral, and, assuming the answer is some ancient lore, then why does it not count in the cut integral?

**Comment by kutschke** [comment]
@oksuzian  - Hi Yuri - let me know if you see this post.

**Comment by brownd1978** [comment]
> * why not do the integral in the BinnedSpectrum class
BinnedSpectrum has to handle a lot of different physics cases. I can only provide a correct implementation for DIO.
> * what is the adjustment of the first bin in the full integral, and, assuming the answer is some ancient lore, then why does it not count in the cut integral?
The Heeke/Szafron spectrum prediction only goes down to 1 MeV. To get the full integral you must assume something in the range 0-1. The authors suggest a linear extrapolation to 0, which is what I implemented. Technically I should include that when calculating the numerator, but there is no physics case for such a low (<1MeV) threshold.

**Review by oksuzian — APPROVED** [review]

**Comment by kutschke** [comment]
@FNALbuild run build test

**Comment by kutschke** [comment]
@oksuzian Yuri, please let me know if you see this.

**Pull request merged**
