### PR TITLE
Added TimeAndPhi cluster finder

### PR DESCRIPTION
**Pull request by bechenard**
The new algorithm is off by default, turn it on one night to check the results on the validation, and we can decide if we want to keep it

### CODE REVIEW

**Comment by kutschke** [comment]
Are you able to talk about this PR at the meeting tomorrow?

**Comment by bechenard** [comment]
Hi Rob,

I’m at cern for a test beam and won’t be able to join the meeting for a few weeks (especially tonight I’m at dinner with friends)

Maybe when I’m back? I asked Dave to run the nightly once to see the impact, I only did tests on a small sample and this is fine but more statistics would be great.

Cheers
Bertrand

**Comment by kutschke** [comment]
> Hi Rob, I’m at cern for a test beam and won’t be able to join the meeting for a few weeks (especially tonight I’m at dinner with friends) Maybe when I’m back? I asked Dave to run the nightly once to see the impact, I only did tests on a small sample and this is fine but more statistics would be great. Cheers Bertrand

Can you recommend a reviewer?  As I understand it we merge this now and it will have no effect on validation since the changes are disabled.  When you return we can complete the review before enabling the new algorithm.  Does that work for you?

   Rob

**Comment by kutschke** [comment]
@FNALbuild run build test

**Comment by kutschke** [comment]
@FNALbuild run build test

**Review by kutschke — APPROVED** [review]
Bertrand will not be available to make a presentation about this PR for a few weeks.  The content of this PR is not enabled by default.  So I will merge it now. 

 There will be a new PR to enable this feature.  Before that is approved, we will need a presentation of this PR at at Wednesday meeting and a proper review.

**Pull request merged**
