### PR TITLE
math.h -> cmath

### PR DESCRIPTION
**Pull request by resnegfk**
math.h -> cmath
Please treat it as a suggestion

### CODE REVIEW

**Comment by ryuwd** [comment]
+1

**Comment by brownd1978** [comment]
What validations have you run (besides compile)?

**Comment by resnegfk** [comment]
I run short samples of g4test_03, ceSimReco and potSim with identical results in all 3 cases

**Comment by kutschke** [comment]
Thanks Krzysztof,

    That's good enough for me.

    Dave: is it enough for you?  Also, I had a look at the diffs and they look good to me.  

Rob

**Pull request merged**
