### PR TITLE
new envset for new MADC and PCIE, no other changes

### PR DESCRIPTION
**Pull request by macndev**

### CODE REVIEW

**Comment by kutschke** [comment]
After you put p024 onto cvmfs, you or I can resubmit the CI .

**Comment by macndev** [comment]
Hi Rob,

I just put p024 onto /cvmfs/, so it should be ready shortly!

-Mackenzie

**Comment by macndev** [comment]
Here are the results for 2k ceSimReco events, there is an exact match: https://mu2e.fnal.gov/atwork/computing/ops/val/plots/PR_788/ce/result.html

**Comment by macndev** [comment]
@FNALbuild run build test

**Review by kutschke — APPROVED** [review]
Thanks Mackenzie, this is ready to merge.  Dave and I will discuss appropriate timing.

**Comment by kutschke** [comment]
@FNALbuild run build test

**Pull request merged**
