### PR TITLE
use CaloSiPMId instead of CaloIDMapper

### PR DESCRIPTION
**Pull request by rlcee**
This is the third and final (from me) update concerning the new calorimeter id classes.  Here I remove CaloIDMapper in favor of CaloSiPMId, and make sure the calo geometry uses CaloConst.hh values where possible.

### CODE REVIEW

**Comment by kutschke** [comment]
Who are appropriate reviewers for this: Giani, Sophie, (Stefano?)?  Others?

**Comment by rlcee** [comment]
> Who are appropriate reviewers for this: Giani, Sophie, (Stefano?)? Others?

I believe CaloIDMapper is Bertrand's code, so I think he would be best, then maybe Giani, then I'm not sure.

**Review by brownd1978 — APPROVED** [review]
This looks like a valuable simplification.

**Review by bechenard — APPROVED** [review]
Looks good (still on vacation so only gave a cursory look but don't want to hold this up)

**Comment by kutschke** [comment]
@FNALbuild run build test

**Pull request merged**
