### PR TITLE
TrackerAligment moved to its own repo

### PR DESCRIPTION
**Pull request by rlcee**
TrackerAlignment is in its own repo.  I've checked that the git history can be accessed.  The new repo builds under Muse.

### CODE REVIEW

**Comment by sophiemiddleton** [comment]
Hi Ray,

Where are the files moved to? I just see the deletes

**Comment by rlcee** [comment]
> Hi Ray,
> 
> Where are the files moved to? I just see the deletes

The code was moved to a new [repo](https://github.com/Mu2e/TrackerAlignment) in the Mu2e organization on github.  The first step was essentially to copy the code there, so there is a no trace of the action here, in Offline.

**Review by sophiemiddleton — APPROVED** [review]
Seems fine

**Comment by kutschke** [comment]
Does anyone plan to build both repos (TrackerAlignment and Offline) under muse and verify that everything still works?  Who should do that?

**Comment by kutschke** [comment]
Thanks Richie,

  Unless it’s a large amount of work that would be wasted, it would be good to fix the fcl now and test while the mechanics are fresh in everyone’s mind.

     Rob

From: Richie Bonventre ***@***.***>
Reply-To: Mu2e/Offline ***@***.***>
Date: Monday, May 10, 2021 at 3:54 PM
To: Mu2e/Offline ***@***.***>
Cc: Rob Kutschke ***@***.***>, Team mention ***@***.***>
Subject: Re: [Mu2e/Offline] TrackerAligment moved to its own repo (#444)


Ray has already tested that it builds. I looked at it briefly, but the alignment fcl is out of date now and needs to be reworked. I'll try to fix it

**Review by bonventre — APPROVED** [review]

**Pull request merged**
