### PR TITLE
React to the name change for the "data decoder" classes in

### PR DESCRIPTION
**Pull request by eflumerf**
artdaq_core_mu2e (no API changes)

### CODE REVIEW

**Comment by eflumerf** [comment]
Follows https://github.com/Mu2e/artdaq_core_mu2e/pull/12

**Comment by kutschke** [comment]
This PR is waiting for https://github.com/Mu2e/artdaq_core_mu2e/pull/12  to be merged, built, installed on cvmfs and the envset updated.  Eric says this work is paused until after the collaboration meeting.

The immediate issue is that build failed because three include files from artdaq_core_mu2e were renamed:

 artdaq-core-mu2e/Data/CalorimeterDataDecoder.hh 
 artdaq-core-mu2e/Data/CRVDataDecoder.hh 
 artdaq-core-mu2e/Data/TrackerDataDecoder.hh

**Comment by kutschke** [comment]
@eflumerf Now that we are past the collaboration meeting, do you have a plan for this?

**Comment by kutschke** [comment]
@eflumerf When I last checked in the plan was to wait until after the collab meeting.   Are the artdaq UPS products ready?  Is this PR still up to date with developments in artdaq products?

**Comment by eflumerf** [comment]
Yes. I have tagged artdaq_core_mu2e v2_00_00 with the changes that this PR needs, and asked for a new environment to be prepared.

**Comment by kutschke** [comment]
> Yes. I have tagged artdaq_core_mu2e v2_00_00 with the changes that this PR needs, and asked for a new environment to be prepared.

Thanks.   I will ask Mackenzie to take the next steps.  When the new envset is ready I will ask you to add to this PR a change to .muse.

**Review by kutschke — APPROVED** [review]
Approved pending the update of .muse once p050 is ready.

**Comment by kutschke** [comment]
@FNALbuild run build test

**Pull request merged**
