### PR TITLE
Small modifications to CrvReco and CrvCoincidence modules

### PR DESCRIPTION
**Pull request by ehrlich-uva**
-small change to the no-fit pulse intervals in the CrvReco module 
-added 2/4 layer coincidence option
-added variables to CrvCoincidence and CrvCoincidenceClusters
-bug fix in CrvCoincidence module
-removed xxxxxCollection.hh files for CrvCoincidence and CrvCoincidenceCluster, which affects a few files outside of CRVResponse

### CODE REVIEW

**Comment by kutschke** [comment]
The error in ceMix has been fixed in a recent merge.  Rerunning the CI now.

@FNALbuild run build test

**Review by brownd1978 — APPROVED** [review]

**Comment by kutschke** [comment]
@oksuzian Yuri: Dave requested that you review this PR.  When do you think you can get to it? 

@ehrlich-uva Ralf: Do you plan to follow up on Dave's suggestion on this PR?

**Review by oksuzian — APPROVED** [review]
Looks good.
I'll be happy to try it out.

**Comment by kutschke** [comment]
@FNALbuild run build tests

**Pull request merged**
