### PR TITLE
Rename mu2e artdaq core

### PR DESCRIPTION
**Pull request by eflumerf**
Changes valid as of artdaq_core_mu2e v1_08_00.

### CODE REVIEW

**Comment by eflumerf** [comment]
It would also be nice to have commit [6461f38](https://github.com/Mu2e/Offline/pull/827/commits/6461f38346c60531ccfa8c7adb36c6604c320b3c) tagged with d10_17_00.

**Comment by rlcee** [comment]
I think this will need
- new version of muse (I will publish)
- new artdaq-core-mu2e products built and published
- new envset with new products (note ongoing PR 828 is changing to p028)

**Comment by kutschke** [comment]
> It would also be nice to have commit [6461f38](https://github.com/Mu2e/Offline/pull/827/commits/6461f38346c60531ccfa8c7adb36c6604c320b3c) tagged with d10_17_00.

I will do this.  But first, please email to me some text to use for the tag comment: is it capturing any particular feature?  Is it being used for any particular study?

**Comment by kutschke** [comment]
> I think this will need
> 
> * new version of muse (I will publish)
> * new artdaq-core-mu2e products built and published
> * new envset with new products (note ongoing PR 828 is changing to p028)

I will start a separate email thread with you, Mackenzie and Ray.

**Comment by kutschke** [comment]
@FNALbuild run build test

**Review by kutschke — APPROVED** [review]

**Pull request merged**
