### PR TITLE
Mu2eII_SM21: Merge main into Mu2eII_SM21 branch

### PR DESCRIPTION
**Pull request by michaelmackenzie**
This is merging a recent version of main (though likely diverged since I started the merge) into the Mu2eII_SM21 branch.
Most of the conflict resolutions were trivial changes in the RMC photon resampling tools (e.g. removing the include for XXX/inc/YYYCollection.hh).
The only one that was beyond this type of change was the resolving of the ProcessCodes, where I consumed one of the
unused process codes as on our branch the code is already defined: `mu2eunused1 --> Mu2eGammaDaughterCut`

I didn't do any testing beyond compiling. Let me know if there's any other testing that should be done!

Best,
Michael

### CODE REVIEW

**Comment by kutschke** [comment]
I will look after merging this when the Mu2e II convenors have signed off.

Do you know the technique for accessing the log file of the failed job?

About what tests you should do.  The Mu2eII conveyors should make that decision.  My recommendation is to do both ceSimReco and count the number of muon stops.  Do you know if ceSimReco works on this branch or has the detector geometry changed enough that it does not work well?   If it does work, run enough events to get 1k or 2k reconstructed tracks.  I also suggest that you also run the job that counts  the number of muon stops to get 10k stopped muons or so.

Do you know how to use val.fcl and valCompare?

**Comment by michaelmackenzie** [comment]
Hi Rob,

> I will look after merging this when the Mu2e II convenors have signed off.
> 
> Do you know the technique for accessing the log file of the failed job?

I typically open this up on a vncserver to avoid having to use a VPN, is there a way to access it without a VPN?
The POT fcl failure is due to the default Production branch not being configured for Mu2e-II, where we have no pbar absorbers and a different target.

> 
> About what tests you should do. The Mu2eII conveyors should make that decision. My recommendation is to do both ceSimReco and count the number of muon stops. Do you know if ceSimReco works on this branch or has the detector geometry changed enough that it does not work well?

I believe this works fine, and runs fine in the build tests.

> If it does work, run enough events to get 1k or 2k reconstructed tracks. I also suggest that you also run the job that counts the number of muon stops to get 10k stopped muons or so.

I'm not sure how many are stopped in the default build tests, but our stopping rate is less than 10% of the Mu2e rate, so probably too few.

> 
> Do you know how to use val.fcl and valCompare?

I am familar (enough) with using these, but I haven't been using these here.

Best,
Michael

**Comment by kutschke** [comment]
Hi Michael,

  If you are logged into any Mu2e to machine, grab the url from the  GitHub review page and type this in a terminal window

curl -O <url>

This will copy to log file into your current working directory.   Since the Mu2e machines are on site, they do not need VPN.

Rob

From: michaelmackenzie ***@***.***>



Hi Rob,

I will look after merging this when the Mu2e II convenors have signed off.

Do you know the technique for accessing the log file of the failed job?

I typically open this up on a vncserver to avoid having to use a VPN, is there a way to access it without a VPN?
The POT fcl failure is due to the default Production branch not being configured for Mu2e-II, where we have no pbar absorbers and a different target.

About what tests you should do. The Mu2eII conveyors should make that decision. My recommendation is to do both ceSimReco and count the number of muon stops. Do you know if ceSimReco works on this branch or has the detector geometry changed enough that it does not work well?

I believe this works fine, and runs fine in the build tests.

If it does work, run enough events to get 1k or 2k reconstructed tracks. I also suggest that you also run the job that counts the number of muon stops to get 10k stopped muons or so.

I'm not sure how many are stopped in the default build tests, but our stopping rate is less than 10% of the Mu2e rate, so probably too few.

Do you know how to use val.fcl and valCompare?

I am familar (enough) with using these, but I haven't been using these here.

Best,
Michael

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Mu2e_Offline_pull_581-23issuecomment-2D921326794&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=ZWM3ug298YLyCls3PAQUDOyDdtcsfrCpVl7wYBFWeSU&s=YZdD9AQSLZUMAuPiHXZNXmgM10E4iBf4UyO2OIVciwg&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABHY5ZSV2TLMKJSECD22NY3UCJ3MVANCNFSM5EFVTWMQ&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=ZWM3ug298YLyCls3PAQUDOyDdtcsfrCpVl7wYBFWeSU&s=6fEgpjdJyIMgD4ICvwWMW6kYgNO7Lm4raCpW58IWy4Y&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=ZWM3ug298YLyCls3PAQUDOyDdtcsfrCpVl7wYBFWeSU&s=hxiSxS5-UuH14NzOQ8D7yPyCPqxH3WvqaNPnfHzJ2T0&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=ZWM3ug298YLyCls3PAQUDOyDdtcsfrCpVl7wYBFWeSU&s=_xdKfgQ8SqIgiBzLvvWTiTDgJMOzPRVaj8Dy6dTndtQ&e=>.

**Comment by michaelmackenzie** [comment]
Hi Rob,

Thanks for the advice! Looking at the failing log file for POT, it's what I expected. There's an error due to `PbarAbsDisk` not being a defined volume, where `Production/JobConfig/beam/prolog.fcl` lists this volume in the DetectorRegionCuts.pars.type list.

Perhaps after this pull request it will be a good time to make a Production/Mu2eII_SM21 branch where we can edit things like
this?

Best,
Michael

**Comment by kutschke** [comment]
Hi Michael,

  The branch Production/Mu2eII_SM21 is there now.  It is far behind main.  Please submit one PR to catch it up to main and a second to add the changes you need for the work at hand.

Rob


From: michaelmackenzie ***@***.***>
Reply-To: Mu2e/Offline ***@***.***>
Date: Friday, September 17, 2021 at 1:42 PM
To: Mu2e/Offline ***@***.***>
Cc: Rob Kutschke ***@***.***>, Assign ***@***.***>
Subject: Re: [Mu2e/Offline] Mu2eII_SM21: Merge main into Mu2eII_SM21 branch (#581)


Hi Rob,

Thanks for the advice! Looking at the failing log file for POT, it's what I expected. There's an error due to PbarAbsDisk not being a defined volume, where Production/JobConfig/beam/prolog.fcl lists this volume in the DetectorRegionCuts.pars.type list.

Perhaps after this pull request it will be a good time to make a Production/Mu2eII_SM21 branch where we can edit things like
this?

Best,
Michael

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Mu2e_Offline_pull_581-23issuecomment-2D922004833&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=lDd9TmzwURLfUYlQMUIwyhmu7rDlAK1MIHEtGSH5IzE&s=dOba3t3-yBoqziOr1O063eSFbheUDSUTMDdwTB6-jh8&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABHY5ZRG46YUUPCA63J6CRTUCODYFANCNFSM5EFVTWMQ&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=lDd9TmzwURLfUYlQMUIwyhmu7rDlAK1MIHEtGSH5IzE&s=MxY5unyGyuDTZo-Q6uTTyV1RRqLvsV45KO4uCsXXnZo&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=lDd9TmzwURLfUYlQMUIwyhmu7rDlAK1MIHEtGSH5IzE&s=63cR6SaPy6nNWfRLTDzGtuviqrQznnhTu-XqDMi75KA&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=lDd9TmzwURLfUYlQMUIwyhmu7rDlAK1MIHEtGSH5IzE&s=cBZSK4DIWZ6DvvmWnbm6A71Rz3BedP1JFbRXOgNdZ4k&e=>.

**Comment by michaelmackenzie** [comment]
Hi Rob,

> Hi Michael, The branch Production/Mu2eII_SM21 is there now. It is far behind main. Please submit one PR to catch it up to main and a second to add the changes you need for the work at hand. 

I made this PR (but accidentally did both in one, sorry!):
https://github.com/Mu2e/Production/pull/96

I can close this and re-open the separate ones, but the changes I added were trivial (3 lines, 1 line in beam/prolog.fcl to fix the POT.fcl issue).

Best,
Michael

**Comment by kutschke** [comment]
Leave it as is.


From: michaelmackenzie ***@***.***>
Date: Friday, September 17, 2021 at 2:53 PM


Hi Rob,

Hi Michael, The branch Production/Mu2eII_SM21 is there now. It is far behind main. Please submit one PR to catch it up to main and a second to add the changes you need for the work at hand.

I made this PR (but accidentally did both in one, sorry!):
Mu2e/Production#96<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Mu2e_Production_pull_96&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=o3rzQfPFWSEJhb9ELUhun6j23zL6ZP1ucWahuZNqq8w&s=fnsPLQFx49gkqKOQnQewnBDTQIhUy-4FQ_0mPCq44pY&e=>

I can close this and re-open the separate ones, but the changes I added were trivial (3 lines, 1 line in beam/prolog.fcl to fix the POT.fcl issue).

**Comment by kutschke** [comment]
@FNALbuild run build test with Mu2e/Production#96

Let's see if this works ...

**Comment by kutschke** [comment]
Hi Michael,

   I did a test merge of your Production PR by hand – I can see that the 3 diff wrt main is just 3 simple lines.

    I also launched a CI test on Offline #581 – I am pretty sure that it will work, maybe by doing the right thing (merging your PR in Mu2eII_SM21) or maybe by accident (merging into main produces the same result with this particular PR).  We can look at the logs afterward and see.

Rob



From: michaelmackenzie ***@***.***>
Date: Friday, September 17, 2021 at 2:53 PM


I can close this and re-open the separate ones, but the changes I added were trivial (3 lines, 1 line in beam/prolog.fcl to fix the POT.fcl issue).

Best,

**Comment by sophiemiddleton** [comment]
I'm good with Michael changes, presuming they are just bringing us upto date with Mu2e main branch so we can benefit from the MDC changes going on

**Comment by kutschke** [comment]
Hi Sophie,

  His PR comments explicitly say that he also modified ProcessCode.hh .  The current state of ProcessCode.hh is very different that it is on head.  I don’t plan on merging until I understand this – which won’t be today.

    There is another problem.  JobConfig will be present in the post-merge Mu2eII_SM21 when it should not be.  This points to a problem in merge mechanics earlier in the process – I have not been able to diagnose it since I don’t know the full sequence of operations.

   This makes me worried that there are other similar issues.   I don’t know of a good way to resolve this.  Does anyone have ideas?  The only idea that I have is to do a trial merge and diff  against the head of main; then ask if the differences make sense?

       Rob


From: Sophie Middleton ***@***.***>
Date: Friday, September 17, 2021 at 3:48 PM


I'm good with Michael changes, presuming they are just bringing us upto date with Mu2e main branch so we can benefit from the MDC changes going on

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Mu2e_Offline_pull_581-23issuecomment-2D922072755&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=RCt2QHAWdsLSFIUFqJCUCROQmNui5PlwjiVGxpkF8aY&s=YcQoFYQQNKa0Y98TWatSgnuA31_69rgKrni_8BQDwAQ&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABHY5ZRBHIEO5JDCYCXFZ6TUCOSSTANCNFSM5EFVTWMQ&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=RCt2QHAWdsLSFIUFqJCUCROQmNui5PlwjiVGxpkF8aY&s=pLWc2FgzV5g3YEt706KHP0-EqjPJywpyhURU7FEgi5k&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=RCt2QHAWdsLSFIUFqJCUCROQmNui5PlwjiVGxpkF8aY&s=gBnzlPUHIUQZtg8o-Y_SXuMdc1pkpJvx3ory3N0QURk&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=RCt2QHAWdsLSFIUFqJCUCROQmNui5PlwjiVGxpkF8aY&s=_xUbpsWj9YwifFo8C9zpSOUlUhr1nTTy1pBMd6FbWYY&e=>.

**Comment by michaelmackenzie** [comment]
Hi Rob,

JobConfig was purposely left in a previous merge to store the fcl that
needed to be moved to the Mu2eII Production branch. After this merge, I can
start moving those to Production and delete the JobConfig directory.
ProcessCode was also significantly changed in the previous merge, where
this change is merging that difference again effectively.

Best,
Michael

**Comment by sophiemiddleton** [comment]
Yes, JobConfig will be moved in the next iteration. 

As for ProcessCode it had previously been modified, is that correct? But there are new modifications too?

**Comment by michaelmackenzie** [comment]
Yes, here I edited it to remove an unused process code to leave our added
process code unmoved. Before, I added that process code I believe. I don't
remember if I changed anything else before as well though.

**Comment by sophiemiddleton** [comment]
Well we used to have Mu2eX but I dont think we need that. I guess we should wait to see what Rob says about this new change, the old change didnt cause any issue on our side

**Comment by michaelmackenzie** [comment]
I think the Mu2eX code is in MCDataProducts/inc/GenId.hh, so we should still be able to generate this process in our datasets.

**Comment by kutschke** [comment]
Thanks for the explanations.  I will merge it.

There is one thing that we need to work out soon; if needed you can put in another PR to resolve it   I believe that you have defined some GenIds are that not now defined in main.   Suppose you generate a data set with the head of the current branch.  Later on may want to merge main  into your branch.  When you do that there can be a conflict - that is the main branch has used some value of the GenId enum that you have also used.   How should you handle this?  I would like to understand this before you generate significant datasets.   One answer might be to always update GenId both branches so that there can never be a conflict that affects data sets that already exist?

**Pull request merged**
