### PR TITLE
Changes in CRV geometry for Wideband simulation

### PR DESCRIPTION
**Pull request by ehrlich-uva**
Added trigger paddles and lead bricks for the Wideband geometry.
Changed one-sided readouts to two-sided readouts at the Wideband geometry.

These changes will not affect the regular Mu2e simulation and reconstruction (but it should still be checked with a nightly validation). The changes are only for the Wideband CRV simulation.

@kutschke Could you please add @oksuzian as a reviewer?

### CODE REVIEW

**Comment by kutschke** [comment]
What is the relationship between this PR and #1334 and #1226?

**Comment by ehrlich-uva** [comment]
@kutschke #1226 is a geometry change for the extracted position (and affects only the extracted position). #1334 is a geometry change for Wideband (and affects only the Wideband CRV simulation).

**Comment by kutschke** [comment]
> @kutschke #1226 is a geometry change for the extracted position (and affects only the extracted position). #1334 is a geometry change for Wideband (and affects only the Wideband CRV simulation).

Can this PR be merged on it's own or does it need the other two.  We don't want to merge #1226 until we make a new branch that is allowed to invalidate existing event-data files.  I think that are comments to respond to on #1334 but I might be misreading it.

**Comment by ehrlich-uva** [comment]
Yes, this PR 1353 can be merged on its own. But it should still be merged as the only PR on a day, so that we can see the effect it has on the nightly validation - just to make sure that it really doesn't change anything.

**Comment by kutschke** [comment]
> Yes, this PR 1353 can be merged on its own. But it should still be merged as the only PR on a day, so that we can see the effect it has on the nightly validation - just to make sure that it really doesn't change anything.

Thanks - I will watch for Yuri's approval and find an appropriate day to merge.

**Comment by ehrlich-uva** [comment]
image
Stack of 4 CRV modules with 2 trigger paddles and a layer of lead bricks.

**Review by oksuzian — APPROVED** [review]

**Comment by kutschke** [comment]
@FNALbuild run build test

@ehrlich-uva are you finished with the planned commits to this PR?

**Comment by ehrlich-uva** [comment]
@kutschke Yes, I'm done.

**Pull request merged**
