### PR TITLE
ExtMon and MARS code

### PR DESCRIPTION
**Pull request by rlcee**
- fixed backwards e_minus and e_plus
- use the utility functions to remove duplicate code
@gaponenko let me know if there is a test procedure, and please review.  This is the last planned code edit on Issue #292

### CODE REVIEW

**Comment by kutschke** [comment]
@gaponenko You will be the only reviewer on this one.  Once you approve, I will merge.

**Comment by kutschke** [comment]
CI invalidated by a recent merge.  Rerun

@FNALbuild run build test

**Review by gaponenko — APPROVED** [review]
Ray, thank you.  The changes look good.  I do not have a test case handy, let's just merge.
Andrei

**Comment by kutschke** [comment]
@FNALbuild run build test

**Pull request merged**
