### PR TITLE
Moved g4study files from Mu2eG4/test & Mu2eG4/fcl to Mu2eG4/g4study

### PR DESCRIPTION
**Pull request by resnegfk**
Moved g4study files to Mu2eG4/g4study and modified content accordingly

### CODE REVIEW

**Comment by resnegfk** [comment]
mu2e/g4study test failure was expected as the file location changed.
That CI test needs to be updated after this PR is merged.

**Comment by kutschke** [comment]
Hi Krzysztof,

  So this means  that the CI tests have passed – right?

  Ray: will fixing the CI tests also fix the nightly or is that a separate step?

Rob


From: Krzysztof Genser ***@***.***>
Reply-To: Mu2e/Offline ***@***.***>
Date: Wednesday, May 12, 2021 at 1:07 PM
To: Mu2e/Offline ***@***.***>
Cc: Rob Kutschke ***@***.***>, Team mention ***@***.***>
Subject: Re: [Mu2e/Offline] Moved g4study files from Mu2eG4/test & Mu2eG4/fcl to Mu2eG4/g4study (#448)


mu2e/g4study test failure was expected as the file location changed.
That CI test needs to be updated after this PR is merged.

**Comment by rlcee** [comment]
> Hi Krzysztof, So this means that the CI tests have passed – right? 
> Ray: will fixing the CI tests also fix the nightly or is that a separate step? Rob

It is two fixes, one in github CI and one in nightly, both simple.  I'll do it as soon as you merge.

**Comment by kutschke** [comment]
Thanks.  I will wait until after the meeting.

From: Ray Culbertson ***@***.***>
Reply-To: Mu2e/Offline ***@***.***>
Date: Wednesday, May 12, 2021 at 1:48 PM
To: Mu2e/Offline ***@***.***>
Cc: Rob Kutschke ***@***.***>, Team mention ***@***.***>
Subject: Re: [Mu2e/Offline] Moved g4study files from Mu2eG4/test & Mu2eG4/fcl to Mu2eG4/g4study (#448)


Hi Krzysztof, So this means that the CI tests have passed – right?
Ray: will fixing the CI tests also fix the nightly or is that a separate step? Rob

It is two fixes, one in github CI and one in nightly, both simple. I'll do it as soon as you merge.

**Review by kutschke — APPROVED** [review]
The failed test is understood.  Fixing it requires a change in the CI code and the nightly validation code.  Ray will look after this post merge.

**Pull request merged**
