### PR TITLE
Adjustments to cosmic fcls to comply with new Mu2eG4 config

### PR DESCRIPTION
**Pull request by oksuzian**

### CODE REVIEW

**Comment by soleti** [comment]
@oksuzian could you remove the `S1DSSTopsCRY.fcl` file? (the one with the typo)

**Comment by brownd1978** [comment]
@FNALbuild run build test

**Review by soleti — APPROVED** [review]
Looks good to me. Maybe in the production release we might want to rename or delete `JobConfig/digitize/OnSpillCosmicDebug.fcl ` though.

**Comment by oksuzian** [comment]
> Looks good to me. Maybe in the production release we might want to rename or delete `JobConfig/digitize/OnSpillCosmicDebug.fcl ` though.

This fcl is for debugging only.
Should I move it to a different location?

**Review by brownd1978 — APPROVED** [review]

**Pull request merged**
