### PR TITLE
Diagnostic Updates

### PR DESCRIPTION
**Pull request by brownd1978**
Add some accessors and utility functions.  Update diagnostics, in particular KalSeed validation.

### CODE REVIEW

**Comment by kutschke** [comment]
Should we expect this PR to trigger work in other repos, such as TrkAna, Stntuple, REve and TrackerAlignment?

**Comment by brownd1978** [comment]
@FNALbuild run build test

**Comment by brownd1978** [comment]
This PR doesn't change any existing interface or algorithm output.

**Comment by kutschke** [comment]
@rlcee Hi Ray, Dave is hoping we can merge this before tonight's validation.  Will you have time to look at it?

**Comment by brownd1978** [comment]
@FNALbuild run build test

**Review by rlcee — APPROVED** [review]

**Pull request merged**
