### PR TITLE
Formatting CosmicCRY

### PR DESCRIPTION
**Pull request by soleti**
`CosmicCRY.cc` contained a very very long line of code after a commit I pushed a while ago. This PR includes CosmicCRY.cc after running `clang-format` on it. If we don't want to make such an extensive change I can just split line 75 (the very long line).

### CODE REVIEW

**Comment by kutschke** [comment]
Thanks Roberto.  Unless we have a merge later today that has physics changes, I will merge this PR and Ray's formatting only PR this evening.

**Comment by oksuzian** [comment]
Roberto, did you run a quick test?

**Comment by soleti** [comment]
Yes, it compiled and ran fine.

**Comment by oksuzian** [comment]
Did you get the same results before and after the changes?

**Comment by soleti** [comment]
I didn't verify that, but these are just formatting changes.

**Comment by kutschke** [comment]
> I didn't verify that, but these are just formatting changes.

I believe that this is tested in the nightly in the cosmicSimReco job.  If there are any issues we will see them then.

**Review by kutschke — APPROVED** [review]

**Comment by oksuzian** [comment]
We may miss a subtle difference, but I'll run a quick test later.

Best, Yuri.

**Pull request merged**
