### PR TITLE
add mu+'s 

### PR DESCRIPTION
**Pull request by pavel1murat**
add mu+'s

### CODE REVIEW

**Review by gaponenko — APPROVED** [review]
Pasha, thank you for submitting this

**Comment by kutschke** [comment]
The failure in cosmicOffspill is understood and unrelated to this PR.  Merging now.

**Comment by brownd1978** [comment]
@FNALbuild run build test

**Comment by kutschke** [comment]
Cleanup after the cosmicOffspill was fixed

@FNALbuild run build test

**Pull request merged**
