### PR TITLE
Stereo hit linear regression fit

### PR DESCRIPTION
**Pull request by brownd1978**
Fit a linear regression to the 3D panel hit points when building stereo hits.  This adds new variables which can be used in background rejection and track finding.  This upgrade changes distributions used in FlagBackgroundHits: that will need to be retrained before this can be merged.

### CODE REVIEW

**Review by myucel-fnal — APPROVED** [review]
Looks great!

**Comment by brownd1978** [comment]
@FNALbuild run build test

**Comment by kutschke** [comment]
Relaunch CI following an intervening merge.

@FNALbuild run build test

**Comment by kutschke** [comment]
At the Comp/Soft today meeting Dave reported that this is ready to merge.

**Pull request merged**
