### PR TITLE
removing TimeMaps (8)

### PR DESCRIPTION
**Pull request by rlcee**

### CODE REVIEW

**Comment by rlcee** [comment]
These were tested with ceSimReco, potSim, cosmicSimReco, and reco

**Comment by kutschke** [comment]
Do I need to test this with Production  261 ?

**Comment by rlcee** [comment]
> Do I need to test this with Production 261 ?

sorry, yes, or just merge Production 261 first

**Comment by kutschke** [comment]
@FNAlLbuild run build test with Mu2e/Production#261

**Comment by kutschke** [comment]
@rlcee can you update this PR with a trivial change so that the CI will run? Or do you know of a way to force rerunning the CI with no changes to PR and no intervening merges?  The CI is not smart enough to recognize that I added the "test with" clause so the rerun is reasonable.

**Comment by kutschke** [comment]
I made and merged a dummy PR to unblock the CI.  Rerunning the CI now:

@FNAlLbuild run build test with Mu2e/Production#261

**Comment by kutschke** [comment]
Ooops.  Typo in previous two attempts.  This time for sure.

@FNALbuild run build test with https://github.com/Mu2e/Production/pull/261

**Review by kutschke — APPROVED** [review]
Given vacations and other commitments I have not found anyone who can review this properly in a timely fashion.  I have looked at it as best I can and do not see any issues.

**Pull request merged**
