### PR TITLE
ComboHitCollection Migration

### PR DESCRIPTION
**Pull request by brownd1978**
re-implement ComboHitCollection using ProductPtr.  Remove StrawHitFlagCollection usage.  Improve interface for accessing parent ComboHits.

### CODE REVIEW

**Comment by brownd1978** [comment]
@FNALbuild run build test with Mu2e/Producton/#265

**Comment by kutschke** [comment]
@brownd1978 is there a natural reviewer for this PR?

**Comment by brownd1978** [comment]
@FNALbuild run build test with Mu2e/Production#265

**Review by kutschke — APPROVED** [review]
I had a quick look and did not see anything to comment on.

**Pull request merged**
