### PR TITLE
CaloPulse Util fix

### PR DESCRIPTION
**Pull request by bechenard**
Fixed a subtle bug that caused the calo digi reco to fail, aargh

### CODE REVIEW

**Review by brownd1978 — APPROVED** [review]

**Comment by brownd1978** [comment]
Hi Namitha, could you please check that this fixes the problem you and Simone observed?  You can either copy the change (1 line) or (better) add his fork as a remote to your own clone and fetch his FCF branch, see the 'Developer' section in https://mu2ewiki.fnal.gov/wiki/GitHubWorkflow#GitHub_Pull_Request_Procedures_and_FNALbuild
for details.

**Comment by bechenard** [comment]
Just to let you know, that will only fix the regular CaloHit maker. The 
Fast algorithm still need a fix.

Bertrand

**Review by NamithaChitrazee — APPROVED** [review]

**Comment by NamithaChitrazee** [comment]
> Hi Namitha, could you please check that this fixes the problem you and Simone observed? You can either copy the change (1 line) or (better) add his fork as a remote to your own clone and fetch his FCF branch, see the 'Developer' section in https://mu2ewiki.fnal.gov/wiki/GitHubWorkflow#GitHub_Pull_Request_Procedures_and_FNALbuild
> for details.

I am so sorry I viewed and checked the change just now. The INFN email ID to which my GitHub notifications are sent had an issue since Thursday.  I have checked with a few events, particularly some events after nevts=3000 where there were no caloclusters earlier. The caloHits are present and the cluster is being formed now.

**Comment by NamithaChitrazee** [comment]
> Just to let you know, that will only fix the regular CaloHit maker. The Fast algorithm still need a fix. Bertrand
> […](#)

Thank you! for looking into this. I am very sorry for the late review.  But, yes the issue looks solved. I checked with some of the events where the caloCluster was absent and it is present now. I shall run the reconstruction with the full MDC2020 10% dataset today to fully ensure.

**Comment by brownd1978** [comment]
Thanks Namitha!

**Pull request merged**
