### PR TITLE
Updated event display

### PR DESCRIPTION
**Pull request by sophiemiddleton**
Updates are minor but previous bug is fixed

### CODE REVIEW

**Comment by kutschke** [comment]
Are there any files in this PR that are not in TEveEventDisplay .  I scanned the file list but that's not very reliable.

**Comment by sophiemiddleton** [comment]
Hi Rob,

I don't think so now, I just fixed the one thing which was not.

**Comment by kutschke** [comment]
Thanks for fixing the spurious change.  Since everything is within TEveEventDisplay, if the CI tests all pass I will merge this.

**Comment by kutschke** [comment]
This still shows as build pending - because of a commit that removed a blank line from setup.sh .  It's now identical to mu2e/master.  So I am merging without rerunning the tests.

**Pull request merged**
