### PR TITLE
fixed CMake build

### PR DESCRIPTION
**Pull request by gianipez**

### CODE REVIEW

**Review by kutschke — CHANGES_REQUESTED** [review]
This PR is a mess.  

It contains changes that are already present in the repo, such as those to RecoDataProducts/src/classes_def.xml and classes.h .

It change behaviour in files not mentioned in the title or the empty description, such as TrkHitReco/src/CombineStereoPoints.cc

Please close this PR and recreate it with just the changes you intend to make.

**Comment by gianipez** [comment]
Hi @kutschke , I think I fixed it and now it's cleaner. Can we proceed?

**Comment by kutschke** [comment]
@FNALbuild run build test

**Comment by kutschke** [comment]
> Hi @kutschke , I think I fixed it and now it's cleaner. Can we proceed?

I have relaunched the CI and will check back after lunch.

**Review by kutschke — APPROVED** [review]

**Pull request merged**
