### PR TITLE
CI test - please ignore

### PR DESCRIPTION
**Pull request by ryuwd**
tests Mu2e/CI#37, Mu2e/codetools#43

### CODE REVIEW

**Comment by ryuwd** [comment]
@FNALbuild please test

**Comment by ryuwd** [comment]
@FNALbuild run code checks

**Comment by ryuwd** [comment]
Everything looks fine.

**Comment by ryuwd** [comment]
@FNALbuild test

**Comment by ryuwd** [comment]
@FNALbuild test

**Comment by ryuwd** [comment]
@FNALbuild test

**Comment by ryuwd** [comment]
Now code checks will run when just before a build test. If trailing whitespace or hard tabs are found, the build will not run until it is fixed.

**Comment by kutschke** [comment]
Hi Ryun,

  Is this live in Offline now?  Is the code base actually clean right now?

Rob


From: ryuwd ***@***.***>
Reply-To: Mu2e/Offline ***@***.***>
Date: Friday, June 18, 2021 at 1:43 PM
To: Mu2e/Offline ***@***.***>
Cc: Rob Kutschke ***@***.***>, Team mention ***@***.***>
Subject: Re: [Mu2e/Offline] CI test - please ignore (#497)


Now code checks will run just before a build test. If trailing whitespace or hard tabs are found, the build will not run until it is fixed.

**Comment by ryuwd** [comment]
>   Is this live in Offline now?  Is the code base actually clean right now?

Yes - but only files that a PR changes are checked. If that's not a good idea I can disable this now.

**Comment by kutschke** [comment]
Hi Ryun,

  If we want to disable this test I think that I need to change the two if statements at:

  https://github.com/Mu2e/codetools/blob/e5f4e013d96dba4c21a9e5cdcba1065189f420d4/bin/github/jenkins_tests/mu2e-offline-code-checks/checks.sh#L18

and

https://github.com/Mu2e/codetools/blob/e5f4e013d96dba4c21a9e5cdcba1065189f420d4/bin/github/jenkins_tests/mu2e-offline-code-checks/checks.sh#L57

Is that correct?

**Comment by ryuwd** [comment]
Hi Rob,

Yes that will work.

**Pull request closed without merging**
