### PR TITLE
Mu2e ii sm21 merge091520

### PR DESCRIPTION
**Pull request by oksuzian**
Updating Mu2eII branch with the latest code development from mu2e/master.
This includes the latest geometry updates by Michael M.
Michael will push the production target geometry for Mu2e-II.

### CODE REVIEW

**Comment by kutschke** [comment]
@FNALBuild run build tests

**Comment by kutschke** [comment]
This PR touches 1020 files?  A cursory look suggest that most of these are just the removal of the obsolete CVS metadata comments, which touched 920 files.   I think it makes sense to split it into 2 or more PRs.  One should be to get Mu2e-II up to date with master, if that's what you want.  Then the add Michael's code as a second PR and any other changes as a third, fourth ...

**Comment by oksuzian** [comment]
>One should be to get Mu2e-II up to date with master

That's all this PR does.
Do you want to split updating part?
If so, how?

**Comment by kutschke** [comment]
Thanks for clarifying.  I mis-read your comment at the start of the PR. I understood "the latest geometry updates" to include changes that are not in master.  I understand now that you are just bringing it up to date with master in preparation for Michael's next round of changes - is that correct?

**Comment by kutschke** [comment]
@FNALbuild run build tests

**Comment by oksuzian** [comment]
Yes, the next step will be for Michael to push the production target geometry he's just implemented.

**Review by sophiemiddleton — APPROVED** [review]
Looks fine - most of the changes are just the author removal and includes tidy ups. Some more serious geometry changes hence needing to put in this PR in the first place.

**Comment by kutschke** [comment]
Yuri confirmed in an email off of the review that the plan is that this branch will never be merged back into master:

> I don’t think we’ll ever merge Mu2eII_SM21 back into master.
> If we have code changes that are relevant for both Mu2e and Mu2e-II, these type of changes will go first to master.
> Then we can merge from master to Mu2eII_SM21.
> Does that make sense?

I wanted to be sure that we do not get loop merges into master.

**Comment by kutschke** [comment]
OK.  This is merged.  Michael can do his PR.

On 9/17/20, 10:51 AM, "Sophie Middleton" <notifications@github.com<mailto:notifications@github.com>> wrote:


@sophiemiddleton approved this pull request.

Looks fine - most of the changes are just the author removal and includes tidy ups. Some more serious geometry changes hence needing to put in this PR in the first place.

**Pull request merged**
