### PR TITLE
removed default parameters in MergeHelices module + extended range of validation histogram

### PR DESCRIPTION
**Pull request by gianipez**
tagging @brownd1978 , @rlcee

### CODE REVIEW

**Review by rlcee — APPROVED** [review]
Seems reasonable

**Review by brownd1978 — APPROVED** [review]
thanks for doing this!

**Comment by brownd1978** [comment]
Earlier Ray told me he wants to increment the version number after validation plots are changed, could you please update:
 _hVer->Fill(9.0);
thanks.

**Comment by rlcee** [comment]
> Earlier Ray told me he wants to increment the version number after validation plots are changed, could you please update: _hVer->Fill(9.0); thanks.

Thank you for keeping this in mind.  Since this is a pretty obscure point, I'll mention the reason here.  The point is that for automated comparisons, if the version changed, some alarms are expected and any report should note that.  Ironically, we are not reporting the version change with the nightly validation report, but in the future this may become more automated and more critical.

**Comment by kutschke** [comment]
@FNALbuild run build test

**Pull request merged**
