### PR TITLE
Thread care

### PR DESCRIPTION
**Pull request by goodenou**
I have made a change that ensures proper cleanup of the worker run managers at the end of the job, even in the case of additional threads being created.

### CODE REVIEW

**Comment by kutschke** [comment]
@FNALbuild run build test

**Comment by goodenou** [comment]
Got it.  Thanks again.  I have made the change.

**Comment by kutschke** [comment]
@FNALbuild run build test

**Comment by kutschke** [comment]
I will merge this in a minute.  When you get a chance I would still like to understand why this works.   Also, I think that Krzysztof has one question waiting for an answer.

**Comment by goodenou** [comment]
I believe I answered all of Krzysztof questions earlier today.  I will send an email to you about why it works.

**Comment by kutschke** [comment]
Hi Lisa,

  He asked why you commented out:

  //NEED TO ADD THIS BACK IN  physicsList_->StorePhysicsTable(storePhysicsTablesDir_);

I know that you added it back.  I was curious why you needed to take it out in the first place?

Rob

**Comment by goodenou** [comment]
I guess I didn’t hit reply all.  The mail wen to just to him:



> Begin forwarded message:
> 
> From: Lisa Goodenough <goodenou@fnal.gov>
> Subject: Re: [Mu2e/Offline] Thread care (#169)
> Date: April 6, 2020 at 11:47:48 AM CDT
> To: Krzysztof Genser <genser@fnal.gov>
> 
> I took it out when I moved the MT Run Manager from the module to the MasterThread.  It was an oversight not to put it back in.  But at least I left a note about it!
>

**Comment by kutschke** [comment]
Thanks.

**Pull request merged**
