### PR TITLE
Crv DAQ updates

### PR DESCRIPTION
**Pull request by ehrlich-uva**
<ul>
<li>Changed the CRVFragment class in artdaq_core_mu2e (PR 2 in artdaq_core_mu2e) to be able to use the newest version of the CRV binary format. This change requires an update to the CRV part of Offline/DAQ, which is done in this PR.</li>
<li>The updates to the CRV part of Offline/DAQ rely on a few files outside of Offline that haven't been merged, yet:
<ul>
<li>CRVFragment.hh and CRVFragment.cc from artdaq_core_mu2e (PR 2)</li>
<li>DTC_Packets.h from mu2e_pcie_utils (PR 3)</li>
<li>FragmentType.hh from artdaq_core_mu2e (PR 1)</li>
<li>DTCEventFragment.hh from artdaq_core_mu2e (PR 1)</li>
</ul>
Offline gets built against versions of these two repositories (artdaq_core_mu2e and mu2e_pcie_utils) that live in artexternals (and not local copies). In order to be able to make updates to the Offline code before these two repositories are updated in artexternals, I temporarily added the relevant files to the Offline/DAQ directory (and changes some of the #includes files). Once the changes in artdaq_core_mu2e and mu2e_pcie_utils have been propagated to artexternals, I will removes these files from Offline. This needs to happen before this PR can be merged.
</li>
<li>Other changes that were introduced to the CRV part of Offline/DAQ (writer/reader)
<ul>
<li>Used the CRV channel database to translate between online and offline channel numbers.</li>
<li>Accepts CRVFragments with variable waveform lengths.
<li>A general overhaul of the code that reads CrvFragments.
</ul>
</li>
<li>By accident, this PR also contains a small change to the EventDisplay and a new geometry, that can be used for CRV modules at Wideband (an almost empty room with 1 CRV module)</il>
</ul>

### CODE REVIEW

**Comment by kutschke** [comment]
@ehrlich-uva Ralf do you know how to access the log file to find the compilation error?  If not, see https://mu2ewiki.fnal.gov/wiki/GitHubWorkflow#GitHub_Pull_Request_Procedures_and_FNALbuild .   The answer is in the first section.

**Comment by ehrlich-uva** [comment]
@kutschke Thank you. I found the problem. I used the wrong #include path for one of the artexternals. It compiled in my workspace, because I had a local copy.

**Comment by kutschke** [comment]
I will launch the CI again.  I see that Eric setup mu2e_pcie_utils in a non-standard way - the package name is not in the include path.  I will discuss that with him separately.

Can you suggest someone who can meaningfully review this PR?

**Comment by kutschke** [comment]
@FNALbuild run build test

**Comment by ehrlich-uva** [comment]
@kutschke Could you please add Eric and Simon as reviewers?

**Comment by kutschke** [comment]
@eflumerf and @corrodis A gentle reminder that you have been asked to review this PR.  Please let me know when you will be able to get to it.  Thanks.

**Comment by kutschke** [comment]
@FNAL build run build test

**Comment by eflumerf** [comment]
This PR needs to wait for new versions of `artdaq_core_mu2e` and `mu2e_pcie_utils`, which are in turn waiting on new versions of the artdaq/otsdaq suites. artdaq should be coming out in the next couple of days, and ots and mu2e early next week.

**Comment by kutschke** [comment]
> This PR needs to wait for new versions of `artdaq_core_mu2e` and `mu2e_pcie_utils`, which are in turn waiting on new versions of the artdaq/otsdaq suites. artdaq should be coming out in the next couple of days, and ots and mu2e early next week.

The CI tests ran successfully.  There is probably no coverage in the CI for this change is that the code builds.  Did you expect it to build before the updates are available?

**Comment by kutschke** [comment]
@FNALbuild run build test

**Comment by ehrlich-uva** [comment]
I temporarily copied the relevant files from the pull requests of artdaq_core_mu2e and mu2e_pcie_utils to make Offline/DAQ compile and work with the new files I get from Simon. One of then is my PR 2 in artdaq_core_mu2e which updates the CRVFragments.

**Comment by kutschke** [comment]
> I temporarily copied the relevant files from the pull requests of artdaq_core_mu2e and mu2e_pcie_utils to make Offline/DAQ compile and work with the new files I get from Simon. One of then is my PR 2 in artdaq_core_mu2e which updates the CRVFragments.

Does this mean that you will need to back these out once the new UPS products are available?

**Comment by ehrlich-uva** [comment]
> > I temporarily copied the relevant files from the pull requests of artdaq_core_mu2e and mu2e_pcie_utils to make Offline/DAQ compile and work with the new files I get from Simon. One of then is my PR 2 in artdaq_core_mu2e which updates the CRVFragments.
> 
> Does this mean that you will need to back these out once the new UPS products are available?

Yes, I have to remove these files and change the #include paths. That's why I marked this PR as a draft.

**Comment by kutschke** [comment]
> Yes, I have to remove these files and change the #include paths. That's why I marked this PR as a draft.

Ok.  Once Eric publishes the new UPS products we can return to this.

**Comment by kutschke** [comment]
@eflumerf and @ehrlich-uva   I would like to understand what happened to this PR.  Did somone close it by hand?  Or was it auto-closed when I merged PR #995 a few minutes ago?  Something else?

@ehrlich-uva  is it correct that this PR is closed? Will you make a follow on PR or was everything you need incorporated into #995 ?

**Comment by ehrlich-uva** [comment]
Hi Rob,

Everything that was in PR 981 was moved to PR 995 and combined with Giani's changes. I should have closed PR 981, but forgot to do it. However, a few minutes ago I got an message that it was merged - even though it was always only a draft.

Ralf

________________________________________

**Comment by kutschke** [comment]
> Hi Rob, Everything that was in PR 981 was moved to PR 995 and combined with Giani's changes. I should have closed PR 981, but forgot to do it. However, a few minutes ago I got an message that it was merged - even though it was always only a draft. Ralf
> […](#)

I poked around some more.  I see that Eric merged your PR into his branch (and then did additional work).  This was done after your most recent commit.  My best guess is that when I merged Eric's PR it auto magically closed your PR on the grounds that it was already included in Eric's.  This makes good sense.

I don't know what GitHub would have done if your most recent change was after Eric's merge.  Hopefully it would have left your PR open.

I now understand this as well as I need to at this time.

**Pull request merged**
