### PR TITLE
move root files to cvmfs

### PR DESCRIPTION
**Pull request by rlcee**
- Move all .root files in Offline to /cvmfs/mu2e.opensciencegrid.org/DataFiles/OfflineData.  
- All access is by data path.  
- could not find code or fcl references to `ParticleID/test/*.root`
- validated with ceSimReco
- no change to nightly validation expected
- satisfies #627
- at some point, data files on cvmfs in BFieldMaps, CRVConditions, Database and PBI could also move under OfflineData because they are all read by Offline algorithm code (as opposed to being art input files)

### CODE REVIEW

**Comment by brownd1978** [comment]
cosmicOffSpill failure:
%MSG-s ArtException:  CaloLikelihood:caloFastPhotonFilter@Construction  01-Nov-2022 11:29:18 CDT ModuleConstruction
cet::exception caught in art
---- search_path BEGIN
  Can't find file "OfflineData/CaloFilters/v7_1_5/caloLH_ce.root"
---- search_path END
%MSG
Art has completed and will exit with status 65.

**Comment by rlcee** [comment]
fixed a typo on cvmfs
@FNALbuild run build test

**Review by kutschke — APPROVED** [review]

**Comment by kutschke** [comment]
@rlcee  This is ready to merge.  Please send out an annoucement describing this change.  When I see it I will merge.

**Comment by rlcee** [comment]
Given this is not what you wanted on #627, I suggest we cancel it

**Pull request merged**
