### PR TITLE
Add no compression option to CompressDigiMCs

### PR DESCRIPTION
**Pull request by AndrewEdmonds11**
Hi Everyone,

I've added an option to CompressDigiMCs to not compress the data products. This will help the CRV group with their studies and is also useful for debugging since we can now turn compression off and not need to change downstream module labels.

This option is off by default, and is turned on with the following fhicl parameter:

`physics.producers.compressDigiMCs.noCompression : true`

This implementation is just a quick fix. I will try to implement this feature better with the more substantial changes required for MDC2020.

Thanks,
Andy

EDIT: As Yuri points out below. To completely leave StepPointMCCollections for the tracker and CRV alone, one needs to add:
```
physics.producers.compressDigiMCs.extraStepPointMCTags: [..., "detectorFilter:CRV"]
physics.producers.compressDigiMCs.crvOutputInstanceLabel : "CRVcompress"
physics.producers.compressDigiMCs.noCompression : true
```
This is because the StepPointMCCollections are not passed directly to this module. I will make sure this is implemented better with the more substantial changes I am making for MDC2020.

### CODE REVIEW

**Review by brownd1978 — APPROVED** [review]

**Comment by oksuzian** [comment]
I can't currently test Andy's modifications.
I'm getting the following error when running from the head.
I can run digi step from the latest tag though.
I see that Bertrand introduced significant chances recently to Filters/src/CompressDigiMCs_module.cc.

%MSG-s ArtException:  PostEndJob 01-Dec-2020 16:39:56 CST ModuleEndJob
---- EventProcessorFailure BEGIN
  EventProcessor: an exception occurred during current event processing
  ---- ScheduleExecutionFailure BEGIN
    Path: ProcessingStopped.
    ---- ProductNotFound BEGIN
      Found zero products matching all selection criteria
        C++ type: std::vector<mu2e::StepPointMC>
        Module label: 'g4run'
        Product instance name: 'calorimeter'
        Process name: (empty)The above exception was thrown while processing module CaloShowerStepMaker/CaloShowerStepMaker run: 2701 subRun: 12934 event: 140
    ---- ProductNotFound END
    Exception going through path TriggerPath
  ---- ScheduleExecutionFailure END
---- EventProcessorFailure END
%MSG
Art has completed and will exit with status 1.

**Comment by AndrewEdmonds11** [comment]
Hi Yuri,

Could you point me to the fcl you are running? I didn't have problems running ceSimReco.fcl. This exception isn't being thrown in CompressDigiMCs so I doubt it's an issue with Bertrand's changes there (which were minimal). It could be a module configuration issue for CaloShowerStepMaker? It's looking for "g4run:calorimeter" StepPointMCs but maybe you need something different for your job?

Cheers,
Andy

**Comment by oksuzian** [comment]
mu2e -c JobConfig/primary/CRY-offspill.fcl -s /pnfs/mu2e/tape/phy-sim/sim/mu2e/s2-dsstops-resampler/092020-hi/art/41/3b/sim.mu2e.s2-dsstops-resampler.092020-hi.002701_00012934.art

**Comment by AndrewEdmonds11** [comment]
Thanks, Yuri. I have to make two changes to CRY-offspull to get it to run. Here's the diff:
```
diff --git a/JobConfig/primary/CRY-offspill.fcl b/JobConfig/primary/CRY-offspill.fcl
index a9747f523..43bb52977 100644

--- a/JobConfig/primary/CRY-offspill.fcl
+++ b/JobConfig/primary/CRY-offspill.fcl
@@ -27,7 +27,7 @@ physics : {
   TriggerPath: [protonBunchIntensity,
                @sequence::CommonMC.DigiSim,
                @sequence::CaloDigiMC.DigiSim,
-               @sequence::TrackerMC.DigiSim,
+               @sequence::TrackerMC.StepAndDigiSim,
                DigiFilter,
                @sequence::CrvDAQPackage.CrvResponseSequence,
                compressDigiMCs]
@@ -67,3 +67,5 @@ physics.producers.CrvPhotons.scintillationYield                 : 11588     //20
 #physics.producers.CrvWaveforms.minVoltage: 0.0075
 #Drop CRV compression
 physics.producers.compressDigiMCs.crvDigiMCIndexMapTag: ""
+
+physics.producers.CaloShowerStepMaker.caloStepPointCollection : [ "detectorFilter:calorimeter" ]
```

The `physics.producers.CaloShowerStepMaker.caloStepPointCollection` parameter fizes the initial issue. And the change of  `@sequence::TrackerMC.DigiSim` to  `@sequence::TrackerMC.StepAndDigiSim` is to solve another error, which is because we recently split the StrawGasStep making and StrawDigi making.

Let me know if you run into any more issue.

**Comment by oksuzian** [comment]
Hi Andy,

Thanks, it works now!

However, the digitization step is now x10 slower. Is that an expected behavior?
I've compared it to:
mu2e -c /cvmfs/mu2e.opensciencegrid.org/Offline/v09_11_00/SLF7/prof/Offline/JobConfig/primary/CRY-offspill.fcl -s /pnfs/mu2e/tape/phy-sim/sim/mu2e/s2-dsstops-resampler/092020-hi/art/41/3b/sim.mu2e.s2-dsstops-resampler.092020-hi.002701_00012934.art

**Comment by oksuzian** [comment]
I have also encountered the following error:
mu2e -c JobConfig/reco/mcdigis_CRY.fcl -s dig.MU2EGRIDDSOWNER.CRY-cosmic-general.MU2EGRIDDSCONF.002701_00012934.art
....
%MSG-s ArtException:  TriggerResultInserter:TriggerResults@Construction  02-Dec-2020 15:06:19 CST ModuleConstruction
cet::exception caught in art
---- LogicError BEGIN
  checkDictionaries: Retrieving list of base classes for type 'mu2e::CaloShowerStepRO' returned a nullptr.
---- LogicError END
%MSG

**Comment by AndrewEdmonds11** [comment]
Hi Yuri,

I don't know whether a 10x slow-down in digitization is expected. Since v09_11_00 it looks like the StrawDigi format was updated and the calorimeter MC was updated among other things. Maybe @bonventre or @bechenard have a better idea?

I also don't see the same error as you when I run the reconstruction on a digi file I created. I will e=mail you the location of my file so you can check if that works for you.

Cheers,
Andy

**Comment by oksuzian** [comment]
> I have also encountered the following error:
> mu2e -c JobConfig/reco/mcdigis_CRY.fcl -s dig.MU2EGRIDDSOWNER.CRY-cosmic-general.MU2EGRIDDSCONF.002701_00012934.art
> ....
> %MSG-s ArtException: TriggerResultInserter:TriggerResults@Construction 02-Dec-2020 15:06:19 CST ModuleConstruction
> cet::exception caught in art
> ---- LogicError BEGIN
> checkDictionaries: Retrieving list of base classes for type 'mu2e::CaloShowerStepRO' returned a nullptr.
> ---- LogicError END
> %MSG

The error is gone after a clean rebuild.
I'm still seeing a slower processing performance compared to v09_11_00

**Comment by bechenard** [comment]
Hi Yuri,

The latest version of the code has a much more realistic version of the 
noise simulation in the calorimeter, which is also slower. Not sure if 
this answers your question, though.

Cheers,

Bertrand

**Comment by bechenard** [comment]
Hi Yuri,

I see I missed this part of the thread. It could be instructive to check 
the speed up before and after the calo MC changes. I would be very 
surprised if this slowed down the code by a factor 10, but if that's the 
case, we should try to do something to improve.

Cheers,

Bertrand

**Comment by oksuzian** [comment]
> Hi Yuri, I see I missed this part of the thread. It could be instructive to check the speed up before and after the calo MC changes. I would be very surprised if this slowed down the code by a factor 10, but if that's the case, we should try to do something to improve. Cheers, Bertrand
> […](#)

Yes, factor of 10 seems large.
Please take a look when you have time.

**Review by oksuzian — APPROVED** [review]
Works as expected.
Just for the refernce, the following needs to be added to CRY-Offline.fcl to disable compression:
physics.producers.compressDigiMCs.extraStepPointMCTags: [..., "detectorFilter:CRV"]
physics.producers.compressDigiMCs.crvOutputInstanceLabel : "CRVcompress"
physics.producers.compressDigiMCs.noCompression : true

**Comment by brownd1978** [comment]
@FNALbuild run build test

**Comment by kutschke** [comment]
@FNALbuild run build tests

**Pull request merged**
