### PR TITLE
mods enabling proper restoration of ions in multistage jobs

### PR DESCRIPTION
**Pull request by resnegfk**

### CODE REVIEW

**Comment by kutschke** [comment]
@FNALbuild run build tests

**Comment by resnegfk** [comment]
Regarding Andrei's comment above:
Although I "philosophically" disagree with not modifying the GenParticle now, I reverted those changes. I also decreased the API change to the SimParticle, responding to another comment by Andrei.

**Comment by resnegfk** [comment]
Andrei and I discussed the request offline and I merged Andrei's code into this pull request

**Comment by kutschke** [comment]
@FNALbuild run build tests

**Pull request merged**
