### PR TITLE
Update StrawRecoFromFragments_module.cc

### PR DESCRIPTION
**Pull request by neshvig10**

### CODE REVIEW

**Comment by kutschke** [comment]
This addresses issue #1012

**Comment by kutschke** [comment]
@FNALbuild run build test

**Comment by kutschke** [comment]
@neshvig10 Thanks for submitting this.  I am sorry but I don't recognize you.  Please tell me who you are working with on Mu2e.  Thanks.

**Comment by neshvig10** [comment]
I'm a open source contributor , trying to make contributions - currently fixing typos

**Comment by kutschke** [comment]
Hi Vigneshwaran,

  Thanks for the contribution.

   Do you have an association with any Mu2e institution?

     Rob



From: Vigneshwaran ***@***.***>
Reply-To: Mu2e/Offline ***@***.***>
Date: Thursday, July 20, 2023 at 11:09 PM
To: Mu2e/Offline ***@***.***>
Cc: Rob Kutschke ***@***.***>, Assign ***@***.***>
Subject: Re: [Mu2e/Offline] Update StrawRecoFromFragments_module.cc (PR #1017)


I'm a open source contributor , trying to make contributions - currently fixing typos

**Comment by neshvig10** [comment]
No ,as of now I don't have any association , but I would like to work with Mu2e

**Comment by kutschke** [comment]
@FNALbuild run build test

**Review by kutschke — APPROVED** [review]
Thanks for this contribution.

Please be aware that when you make a contribution you are agreeing to the terms of the LICENSE. 

You can learn more about the Mu2e experiment at https://mu2e.fnal.gov .

**Pull request merged**
