### PR TITLE
added Wideband MC and calib/reco of Wideband data

### PR DESCRIPTION
**Pull request by ehrlich-uva**
added/updated modules/scripts/... to handle simulations of stacks of CRV modules at the Wideband building.
added/updated modules/scripts/... to calibrate and reconstruct data collected from CRV modules at the Wideband building

details about the calibration and reconstruction of Wideband data can be found at doc-db 47311

### CODE REVIEW

**Comment by ehrlich-uva** [comment]
@kutschke There are still a few minor things that I would like to add, and I need to fix the merge conflicts.

**Comment by kutschke** [comment]
> @kutschke There are still a few minor things that I would like to add, and I need to fix the merge conflicts.

Thanks.  Please give me a heads up when it's time for me to run the CI.

**Comment by kutschke** [comment]
@ehrlich-uva I see that you cleared the merge conflcits.  THanks.  I will run the Ci.

What else, if anything, is needed before you are done?

@FNALbuild run build test

**Comment by ehrlich-uva** [comment]
@kutschke I'm done with my updates. However, our database discussion may result in additional changes.

**Comment by kutschke** [comment]
@FNALbuild run build test

**Comment by kutschke** [comment]
@FNALbuild run build test

Force retest because of intervening merges

**Comment by kutschke** [comment]
I am checking in.   In the dsicussion or #1181 there was a comment from Ray, quoting Ralf and following up:

>@rlcee The CRV time offsets need to have different sim and reco tables.
>OK, in the meeting I heard it as sometime in the future. I recommend finishing the CRV PR as is, to make the reco prodition and then I can follow up with the Sim copy.

Based on that, I proipose the following as the way forward:

1. I will merge Offline 1163 as is
2. I will NOT merge Production 287 at this time
3. Ralf and Ray will create the sim table and put it in the database, which may mean intervening PRs.
4. Ralf will update PR 287 to use the DB, not a text file and I will merge ( or close 287 and open a new one if that makes more sense).

@ehrlich-uva and @rlcee : does this work for you?

**Comment by ehrlich-uva** [comment]
@kutschke This plan works for me.

**Pull request merged**
