### PR TITLE
New deltaFunctionGenerator module.

### PR DESCRIPTION
**Pull request by gaponenko**
Adding a new event generator, no effect on validation.

### CODE REVIEW

**Comment by kutschke** [comment]
What features does this add that are not already prsentHow is this different that the existing particle gun generator?

**Comment by gaponenko** [comment]
Hi Rob,

The new module supports one use case as simply and efficiently as possible, instead of trying to support multiple different use cases.
I want to use it with a g4study setup.   An existing module that could work is EventGenerator, but it requires a separate SimpleConfig file; an overhead I would like to avoid.
Some generators are configurable from fcl, like PrimaryProtonGun, but they are tied to the full Mu2e geometry and can not be used with g4study.

The new generator is fully multi-threaded, unlike any of the existing generators.  Perhaps a small impact in practice, but why compromise if we don't have to?
The laptop I am running this on has 20 cores, so enabling MT in general makes a lot of sense.

An important factor for me is also using "code that is so simple there are obviously no bugs, instead of code so complicated there are no obvious bugs" whenever I can.

Andrei

________________________________________

**Review by kutschke — COMMENTED** [review]
In the fcl comments, please add units and, where appropriate, "in the Mu2e coordinate system".

**Comment by gaponenko** [comment]
Done, please take a look.
Andrei

________________________________________

**Comment by gaponenko** [comment]
Good catch, fixed!

________________________________________

**Review by kutschke — APPROVED** [review]
Thanks for making the changes.

**Comment by kutschke** [comment]
@FNALbuild run build test

**Pull request merged**
