### PR TITLE
Time and phi

### PR DESCRIPTION
**Pull request by bechenard**
This commit has 
 - new TimeAndPhi clusterfinder algorithm, but the *old version* is still used as default for now.
 - updated TimeClusterFinder and TrkTimeCalculator to use ConfigTable (and cleaning unused hearders)
- fixed a small bug in TrkTimeCalculator and other minor cleanup

### CODE REVIEW

**Comment by ryuwd** [comment]
Hi, 

FNALbuild has noticed that the times on your commits are about 10 minutes ahead of the correct time (timezone accounted for). Is the clock on the computer that you're committing from synchronised and up to date?

Thanks! Ryun

**Comment by ryuwd** [comment]
Nevermind - looks like it fixed itself!

**Comment by brownd1978** [comment]
@FNALbuild run build test

**Comment by ryuwd** [comment]
I re-ran the job from Jenkins and the git merge conflict is persisting. Try merging in or rebasing onto the latest upstream master branch ?

**Pull request merged**
