### PR TITLE
updated CRV coincidence finder

### PR DESCRIPTION
**Pull request by ehrlich-uva**
This pull request accomplishes the following things:
-Removes crv noise hits (not associated with a SimParticle) in CrvCoincidenceClusterMatchMC to prevent problems in downstream modules.
-Fixes a bug in the crv geometry file, that described how individual crv sectors are connected with each other for the purpose of the coincidence finder. This change does not change the geometry itself and has no impact on the simulation.
-Updated the algorithm for the crv cluster finder.

Some test results:
-Still finds the same number of events with coincidences when running cosmicSimReco.fcl.
-The coincidence cluster window lengths produced by the reco validation jobs got reduced, which is necessary to keep the dead time down.

### CODE REVIEW

**Comment by kutschke** [comment]
@FNALbuild run build test

**Review by brownd1978 — APPROVED** [review]
This is approved for now because it is urgent, but the next PR to CRVResponse needs to improve the parallel configuration parameters by putting them in a struct, and using the art embedded table technology to enter them coherently in fcl.

**Comment by ehrlich-uva** [comment]
@brownd1978 I will change it in the next PR.

**Comment by ehrlich-uva** [comment]
@brownd1978 I changed the fcl parameter structure. Testing it now. I can commit the change within the next hour.

**Comment by ehrlich-uva** [comment]
@brownd1978 done

**Review by brownd1978 — APPROVED** [review]
Thanks Ralf!

**Comment by kutschke** [comment]
@FNALbuild run build test

**Review by kutschke — APPROVED** [review]

**Pull request merged**
