### PR TITLE
Mu2eII_SM21: production target yields updates

### PR DESCRIPTION
**Pull request by michaelmackenzie**
Updates to the Mu2e-II style production target options used in the target yield estimates for the Snowmass 2021 study

### CODE REVIEW

**Review by sophiemiddleton — APPROVED** [review]
Seems fine to me

**Comment by kutschke** [comment]
@michaelmackenzie please fix the whitespace issues and update the PR.  For information see https://mu2ewiki.fnal.gov/wiki/Editors

**Comment by michaelmackenzie** [comment]
Hi Rob,

I think some tabs were inserted from copying/pasting sections of code that had tabs in it already. I removed tabs/whitespace from all of ProductionTargetMaker, where there were many tabs/instances of trailing whitespace. Is this what you were referring to?

Best,
Michael

**Comment by kutschke** [comment]
To find the whitespace errors, look at the GitHub conversation page for the PR.  At the bottom of the CI report there is a whitespace report.  Click on the link to see it.  You need to be on VPN for it to work.  The content is:

```
Mu2eG4/geom/ProductionTarget_Mu2eII_Conveyor_W_v01.txt:300: trailing whitespace.
+  4135.6514 
Mu2eG4/geom/ProductionTarget_Mu2eII_Conveyor_W_v03.txt:301: trailing whitespace.
+  4135.6514 
Mu2eG4/geom/ProductionTarget_Mu2eII_Conveyor_v02.txt:17: trailing whitespace.
+int    targetPS.Mu2eII.conveyor.nballs        = 28; 
Whitespace check detected format errors
```

Please let me know when I should rerun the CI.

**Comment by michaelmackenzie** [comment]
Hi Rob,

Thank you! I didn't realize there was a whitespace report in the CI report. I've removed the trailing whitespace from the production target configs.

Best,
Michael

**Comment by kutschke** [comment]
@FNALbuild run build test

**Comment by kutschke** [comment]
@michaelmackenzie  I have attached a the output of gitk --topo-order for Michael's branch  
[Michael.pdf](https://github.com/Mu2e/Offline/files/10189796/Michael.pdf)

You can see that your work started from tag s01_03_00 .  You did 6 commits in February.  I presume that "Add a geometry file using he MARS carbon target density" is the one that you used to do the work with Stefan.  Is that correct?

**Comment by michaelmackenzie** [comment]
Hi Rob,

I'm not sure I exactly follow what you're asking, but yes, I initially committed much of this work in February but then never created a PR for it. I believe I committed several target changes/configurations (2 different carbon density runs, a few different tungsten configurations). I believe some of the ntuples were created a different commits, such as adding the new carbon density option was after the initial carbon density ntuple was created. The final commit should contain all of the information to re-produce the data.

Let me know if there's anything else you would like me to clarify!

Best,
Michael

**Comment by kutschke** [comment]
I think we need to get Stefan into this.  I will answer on that email thread.

**Comment by kutschke** [comment]
There was a conversation on a separate email thread.  I will go ahead with the merge but I won't make any tags until advised by the Michael and Stefan which commits to tag in order to mark the code that they used.  Note that the post-merge head is not the correct commit to tag; not is the pre-merge head of Michael's branch.  Both contain commits that were not part of the work reported in Stefan's paper.

**Pull request merged**
