### PR TITLE
added more c'tor, operator deletions and const refs

### PR DESCRIPTION
**Pull request by resnegfk**
A small follow up on PR#533

### CODE REVIEW

**Comment by kutschke** [comment]
I have some clues and guesses.

g4test_03MT died with return code 139.  Subtract 128 to get the unix signal number, 11.  And that is segmentation violation. Once upon a time it was important not to hold parameter sets or configuration objects by reference - they were transients deleted after the c'tor returned.  I don't know if that is still true.   Please check with Kyle.  The other possibility is that with your changes these objects are stored in master thread local memory and something from a worker thread eventually tries to use it?

Note that ceSimReco and ceSteps run Mu2eG4_module but that muDauSteps runs Mu2eG4MT_module.  ceDigi does not run G4.  And ceMix fails because it gets it's output from muDauSteps.

I did not check the other G4 jobs for G4MT vs nonMT. 

So that's where I would start to track this down.

**Comment by kutschke** [comment]
Also, what tests did you run?  Did you run any that did a valCompare before and after?

**Comment by resnegfk** [comment]
@FNALbuild run build test

**Comment by resnegfk** [comment]
> I have some clues and guesses.
> 
> g4test_03MT died with return code 139. Subtract 128 to get the unix signal number, 11. And that is segmentation violation. Once upon a time it was important not to hold parameter sets or configuration objects by reference - they were transients deleted after the c'tor returned. I don't know if that is still true. Please check with Kyle. The other possibility is that with your changes these objects are stored in master thread local memory and something from a worker thread eventually tries to use it?
> 
> Note that ceSimReco and ceSteps run Mu2eG4_module but that muDauSteps runs Mu2eG4MT_module. ceDigi does not run G4. And ceMix fails because it gets it's output from muDauSteps.
> 
> I did not check the other G4 jobs for G4MT vs nonMT.
> 
> So that's where I would start to track this down.

Reading this only now. This was a segfault in: 
mu2e::Mu2eUniverse::Mu2eUniverse (this=0x69876a0, debug=...) at Offline/Mu2eG4/src/Mu2eUniverse.cc:35
35	    _g4VerbosityLevel(debug.diagLevel()) in the MT mode

**Comment by kutschke** [comment]
> Reading this only now. This was a segfault in:
> mu2e::Mu2eUniverse::Mu2eUniverse (this=0x69876a0, debug=...) at Offline/Mu2eG4/src/Mu2eUniverse.cc:35
> 35 _g4VerbosityLevel(debug.diagLevel()) in the MT mode

Thanks - that makes sense.  It's trying to use the config object and I think my guess is right - it's long since deleted.

**Review by kutschke — APPROVED** [review]
I would like to let this go through the nightly validation with no other merges.

**Comment by resnegfk** [comment]
As this PR (inspired by the PR#533 review comments) is only about "unused" c'tors and operators and how objects are held,
it should not cause any changes of any of results, (but I cannot foresee how the known instabilities are going to be affected by it).

**Comment by kutschke** [comment]
I don’t expect anything either – just being cautious.

From: Krzysztof Genser ***@***.***>
Reply-To: Mu2e/Offline ***@***.***>
Date: Tuesday, August 24, 2021 at 8:28 PM
To: Mu2e/Offline ***@***.***>
Cc: Rob Kutschke ***@***.***>, Assign ***@***.***>
Subject: Re: [Mu2e/Offline] added more c'tor, operator deletions and const refs (#567)


As this PR (inspired by the PR#533 review comments) is only about "unused" c'tors and operators and how objects are held,
it should not cause any changes of any of results, (but I cannot foresee how the known instabilities are going to be affected by it).

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Mu2e_Offline_pull_567-23issuecomment-2D905097076&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=UHdj08Ao2pW1QjXl-CDk75qcan6h1liDQyegOth0Qek&s=X5Gztws_dGMpGm2Ic5R7orXErJWGJd8u8Ky9z5loCic&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABHY5ZVVVQDLYSDIR22HNGTT6RBJ5ANCNFSM5CXVTFYQ&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=UHdj08Ao2pW1QjXl-CDk75qcan6h1liDQyegOth0Qek&s=azd2bUQxAO_3a-gUkYfIlYKOEHcpuxpSCvXEWyyLLBo&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=UHdj08Ao2pW1QjXl-CDk75qcan6h1liDQyegOth0Qek&s=D7ztOXRQCPxLf3WobT_Gihj1oiQYhYeshi1NwJ6vjUo&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26utm-5Fcampaign-3Dnotification-2Demail&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=UHdj08Ao2pW1QjXl-CDk75qcan6h1liDQyegOth0Qek&s=4tYxelXT0kzoN_fW7HDoCf4fCr_S0S3uWnl8xKCGs1k&e=>.

**Pull request merged**
