### PR TITLE
Edit TrackerAlignment README, also test new CI scripts

### PR DESCRIPTION
**Pull request by ryuwd**
PR to test cleaned up CI scripts in Mu2e/codetools#21

### CODE REVIEW

**Comment by ryuwd** [comment]
@FNALbuild test

**Review by kutschke — COMMENTED** [review]
Ryun:  the comment says that you updated the README and that you tested new CI scripts.  I don't see any scripts changed in this PR.  Should I see changed scripts?

**Comment by ryuwd** [comment]
@FNALbuild test

**Comment by ryuwd** [comment]
> Ryun: the comment says that you updated the README and that you tested new CI scripts. I don't see any scripts changed in this PR. Should I see changed scripts?

Hi Rob, 

The changed scripts + explanation of changes are here: https://github.com/Mu2e/codetools/pull/21

**Comment by kutschke** [comment]
Ok.  So I understand the comment about new scripts to mean that one of the side effects of updating the README is to trigger the tests in order to exercise the recent updates to the code tools repo.  Is that right?

**Comment by ryuwd** [comment]
Test results now show more information in the "checks" area.
image


It should also be simpler now to add / remove tests by adding / removing the FCL file path, the name of the test, and the number of events defined at the start of this file:
https://github.com/Mu2e/codetools/blob/master/bin/github/jenkins_tests/mu2e-offline-build-test/job.sh#L11-L16

**Comment by ryuwd** [comment]
> Ok. So I understand the comment about new scripts to mean that one of the side effects of updating the README is to trigger the tests in order to exercise the recent updates to the code tools repo. Is that right?

Yes this is correct. If it makes sense to merge the README changes too that's fine. If not it can go into the new TrackerAlignment muse-friendly repository once that is created.

**Comment by kutschke** [comment]
I am happy to merge this once the two reviewers have approved it.   If you prefer, I can leave it open as a vehicle for testing and merge when testing is done. Your call.

**Comment by ryuwd** [comment]
Thanks Rob!

I have one more test to do to get the overlaps tests to show again, and then I should be finished.

**Comment by ryuwd** [comment]
Oops - sorry. I triggered this test before the fix got merged.

**Review by sophiemiddleton — APPROVED** [review]
looks good to me

**Comment by kutschke** [comment]
This changes only README.md so I am not going to rerun tests before merging.  We had kept it open for a few days to use as a testbed for updates to the CI system.  That is now complete so I am merging now.

**Pull request merged**
