### PR TITLE
new checks and features for overlapCheck.sh

### PR DESCRIPTION
**Pull request by rlcee**
- at Rob's request, add two checks for gdml errors
- added a couple of features
- recognize Muse location of build of gdml
- should be backwards compatible
- once merged, I'll update nightly and CI to use new features
- and remove obsolete codetools/bin/rootOverlaps.sh

### CODE REVIEW

**Comment by kutschke** [comment]
@rlcee can you please remind me how to run this test?

**Comment by rlcee** [comment]
> @rlcee can you please remind me how to run this test?

muse setup
overlapCheck.sh -h
if help is not clear, we can improve it.

**Review by kutschke — APPROVED** [review]
I tested it with known good and known bad gdml files.  it works as expected.  Thanks.

**Review by resnegfk — APPROVED** [review]
A nice enhancement

**Pull request merged**
