### PR TITLE
Dummy change for testing.

### PR DESCRIPTION
**Pull request by kutschke**
A dummy change to see if Eric can approve this one.

### CODE REVIEW

**Comment by kutschke** [comment]
@eflumerf I just makde PR #837 with dummy changes.  Please see if you can approve this one.

**Review by eflumerf — APPROVED** [review]
test

**Comment by kutschke** [comment]
Bummer.  That did not work.  I need to get a few other things done before the end of the day.  I will get back to this when I can.

**Review by kutschke-non-admin — APPROVED** [review]
Approve from non-admin account

**Comment by kutschke-non-admin** [comment]
> Just a thought, if you were changing permissions at the org level, it's possible that the repo itself has permissions overriding them (or vice versa).

Thanks.  I had looked at that on Friday. I had to uncheck some org level controls to un-grey the repo level controls.  Can yo see this: https://github.com/Mu2e/Offline/settings/code_review_limits  or can only admins see it?

**Comment by eflumerf** [comment]
Only admins.

**Review by kutschke-non-admin — APPROVED** [review]
Try again after changing org level back to no limits.

**Comment by kutschke** [comment]
The testing is done.  Closing this PR.  Below is what I learned:

  I have found the relevant pieces of GitHub Docs for our ongoing approval issue.  The bottom line is this: if we require a minimum number of approvals before merging is enabled, then the only approvals that count must come from people with write or admin access.   If someone with only read access gives an approval, then their approval is recorded with a grey checkmark (not green) in the upper right of the conversation page and the merge remains blocked.
 
   The easiest way to proceed is this: if none of the requested reviewers have write or better access, then the assigned merger should wait until the grey check marks are collected and then add their own approval with a comment saying that all grey check marks are there.  Then they can merge.   Does that work for you?
 
 I have also read about CODEOWNERS files.  People in CODEOWNERS files must have write access to the full repo.  So I don’t think that this helps us.
  
   Some of the relevant sections of the GitHub docs are listed below
 
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews
 
This clearly states that if we require a minimum number of approving reviews, then approving reviews must come from people with write or admin access to the repo.
 
There is another statement at:
 
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#require-pull-request-reviews-before-merging
 
which says that approvers must be from: “people with write permissions in the repository or from a designated code owner.”  If you follow up on “designated code owners”, it says that they must be users with write or better access.
 
What was confusing me on Friday was that the “Code Review Limits” pages for organizations https://github.com/organizations/Mu2e/settings/code_review_limits  and repos: https://github.com/Mu2e/Offline/settings/code_review_limits  talk about allowing people with “read or better: to approve PRs.  I believe that these settings are only active when the setting for requiring a minimum number of reviews is in active; but I don’t see an explicit statement to that effect.

Also,  from: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#require-pull-request-reviews-before-merging

If a person with admin permissions chooses the Request changes option in a review, then that person must approve the pull request before the pull request can be merged. If a reviewer who requests changes on a pull request isn't available, anyone with write permissions for the repository can dismiss the blocking review.

And:
 
Even after all required reviewers have approved a pull request, collaborators cannot merge the pull request if there are other open pull requests that have a head branch pointing to the same commit with pending or rejected reviews.  Someone with write permissions must approve or dismiss the blocking review on the other pull requests first.

 In this part, the phrase "same commit" is ambiguous to me.  I think it means that if PR2 is based off of PR1 and PR1 is based off of Offline/main, then, if there is an outstanding approval on PR2, the merge of PR1 will be blocked.  It does not mean that if PR1 and PR2 are both starting from the same commit on Offline/master then one can block the other; I verified that by testing.

**Pull request closed without merging**
