### PR TITLE
Python Strawid

### PR DESCRIPTION
**Pull request by rlcee**
Here is the python using the PyWrap interface to the c++ StrawId class.  I don't feel strongly if you use it or not.  One might say that mixing code is an unnecessary complication, or one might say it is our future..  If merged, should have no effect on validation.

### CODE REVIEW

**Comment by kutschke** [comment]
> Here is the python using the PyWrap interface to the c++ StrawId class. I don't feel strongly if you use it or not. One might say that mixing code is an unnecessary complication, or one might say it is our future.. If merged, should have no effect on validation.

I think that there is value in this approach - it reduces points of maintenance, although this example is very unlikely to ever change.   The other option would be to code-gen both python and c++ but that would require an investment in new infrastructure.  I think that this is right way to go unless we discover issues.

**Review by brownd1978 — APPROVED** [review]

**Comment by kutschke** [comment]
@bonventre a gentle reminder that this is in your queue

**Comment by kutschke** [comment]
@FNALbuild run build test

**Comment by kutschke** [comment]
@bonventre a gentle reminder that this is in your queue

**Comment by bonventre** [comment]
Hey sorry for the delay, I've been out on vacation. We may want to add StrawStatus as well

**Comment by rlcee** [comment]
> Hey sorry for the delay, I've been out on vacation. We may want to add StrawStatus as well

The interface to StrawStatus is fairly complicated (c++ vs python-wise) and it take a bit of work to get some methods working. Are you planning to use it in a particular way?  Like input a int bit word and test by string bit by name?

**Comment by bonventre** [comment]
I think then lets wait until a specific use case comes up

**Review by bonventre — APPROVED** [review]

**Pull request merged**
