### PR TITLE
Fixed calo pusle root file and remove superfluous include directives

### PR DESCRIPTION
**Pull request by bechenard**

### CODE REVIEW

**Comment by kutschke** [comment]
@FNALbuild run build tests

**Review by brownd1978 — APPROVED** [review]
reviewing binary data is tricky; can you provide a listing in the comments?  I think long-term we should move this file to /cvmfs.

**Review by kutschke — APPROVED** [review]
I did a trial merge of this PR into the head of master and built it.  I confirm that the following runs to completion with no errors:

 mu2e -c Validation/reco.fcl -n 10 -s /pnfs/mu2e/persistent/users/mu2epro/valjob/reco_210511/dig.brownd.CeEndpointMix.MDC2020c.001201_00000000.art

Presuming that the CI completes successfully. I approve.

**Comment by kutschke** [comment]
ceSimReco also failed on PR 454. Helenka says that if you do a clean build of the head of Offline with a clean clone of Production, it fails.

**Comment by bechenard** [comment]
And with the fix?

**Comment by kutschke** [comment]
I agree.  I would like to get all of the .root files that contain calibration information out of the git repos.

I have created issue: https://github.com/Mu2e/Offline/issues/475



From: David Brown ***@***.***>
Reply-To: Mu2e/Offline ***@***.***>
Date: Friday, June 4, 2021 at 4:11 PM
To: Mu2e/Offline ***@***.***>
Cc: Rob Kutschke ***@***.***>, Comment ***@***.***>
Subject: Re: [Mu2e/Offline] Fixed calo pusle root file and remove superfluous include directives (#474)


@brownd1978 approved this pull request.

reviewing binary data is tricky; can you provide a listing in the comments? I think long-term we should move this file to /cvmfs.

**Comment by bechenard** [comment]
I believe this is something Dave or you can take care of, right?

**Comment by kutschke** [comment]
I can duplicate the ceSimReco crash interactively in the build with this fix.  Looking at it now.

**Comment by kutschke** [comment]
It looks like some of the changes on the last PR on Production did not get propagated into Validation .   I am iterating on it now

**Comment by kutschke** [comment]
We ( or Ray) will organize it when it’s priority bubbles up.

From: Bertrand Echenard ***@***.***>
Reply-To: Mu2e/Offline ***@***.***>
Date: Friday, June 4, 2021 at 4:38 PM
To: Mu2e/Offline ***@***.***>
Cc: Rob Kutschke ***@***.***>, Assign ***@***.***>
Subject: Re: [Mu2e/Offline] Fixed calo pusle root file and remove superfluous include directives (#474)

I believe this is something Dave or you can take care of, right?

**Comment by brownd1978** [comment]
@FNALbuild run build tests

**Pull request merged**
