### PR TITLE
switched CalHelixFinder and CalTeimPeakFinder from EDFilter to EDProducer

### PR DESCRIPTION
**Pull request by gianipez**

### CODE REVIEW

**Comment by gianipez** [comment]
We need to use mu2e_trig_config PR #41

**Review by brownd1978 — APPROVED** [review]

**Comment by brownd1978** [comment]
@FNALbuild run build test with Mu2e/mu2e_trig_config#41

**Comment by brownd1978** [comment]
let me know if mu2e_trig_config#41 is ready to merge, then we can merge these together.

**Comment by gianipez** [comment]
hello @brownd1978 , YES the mu2e_trig_config#41 PR is ready as well. Thanks

**Pull request merged**
