### PR TITLE
new envset p043 to pick up new ADCM for STM

### PR DESCRIPTION
**Pull request by macndev**

### CODE REVIEW

**Comment by eflumerf** [comment]
Can this commit be tagged `d10_22_01`? It will correspond to our UPS product which will be built soon...

**Comment by macndev** [comment]
Hi, Eric. I am not too sure how to tag a commit. Should I be the one doing the tagging or should that be done by someone else? If so, I need instructions on how to tag.

**Comment by eflumerf** [comment]
I think that's something that's usually done by @kutschke

**Comment by kutschke** [comment]
Hi Eric,

  I will do the tag after the merge.  I need to discuss with Dave about which of the outstanding PRs we will merge today.

Rob

From: eflumerf ***@***.***>
Date: Thursday, June 29, 2023 at 3:03 PM
To: Mu2e/Offline ***@***.***>
Cc: Robert K Kutschke ***@***.***>, Mention ***@***.***>
Subject: Re: [Mu2e/Offline] new envset p043 to pick up new ADCM for STM (PR #996)

I think that's something that's usually done by @kutschke<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_kutschke&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=Zi5IH-k2_JiK_Wipiv3pwwSXO9UNaHiLP8sisfPz__k&m=_wlU0Ic9cnQHx7_QgMEuDkAu30x_4e7tIRIXky9VxsnfXowyDbeRkRnV_POHBbBF&s=a6R2m8P5NHLDAE5957kNaetl_yhGRgGwLJKH5BbQZqI&e=>

**Review by kutschke — APPROVED** [review]
We do not expect any changes to validation from this PR because there is no coverage.  Mackenzie reported that 1000 events of ceSimReco matched exactly.

**Pull request merged**
