### PR TITLE
checking CI change

### PR DESCRIPTION
**Pull request by HCasler**

### CODE REVIEW

**Comment by HCasler** [comment]
@FNALbuild how are you

**Comment by HCasler** [comment]
@FNALbuild test

**Comment by HCasler** [comment]
@FNALbuild with Mu2e/Production#169

**Comment by HCasler** [comment]
@FNALbuild run bulid tests

**Comment by HCasler** [comment]
@FNALbuild test with Mu2e/Production#169

**Comment by HCasler** [comment]
OK, those all got the "confused" reaction,  as they should. Now testing the correct command:

@FNALbuild run build tests

**Comment by HCasler** [comment]
OK, I think this change to CI did what it was supposed to

**Comment by kutschke** [comment]
> OK, I think this change to CI did what it was supposed to

Yes it does.  Thanks for the thorough testing.

**Pull request closed without merging**
