### PR TITLE
added some functions in TrkRecoMcUtil

### PR DESCRIPTION
**Pull request by gianipez**
I need these new functions in a diagnostic tool that I've been developing with a student for a new module we plan to commit in the coming weeks/months.

### CODE REVIEW

**Comment by kutschke** [comment]
@gianipez is there anyone who can meaningfully review these changes?  Do you know if these changes will affect the nightly validation plots?

**Comment by kutschke** [comment]
@gianipez .  I merged Ray's PR #841 ( change use of Root TFORM  to std::ostringstream ).  This created conflict with this PR.  Please resolve it - it should be trivial.

**Comment by kutschke** [comment]
Here are the review assignments:

andrei
       Analyses/src/pbars1hist_module.cc
       EventGenerator/src/ExtMonFNALBoxGenerator_module.cc
       Filters/src/EMFBoxHitsFilter_module.cc
       Sources/src/ExtMonFNALMARSUtils.cc
       Sources/src/FromExtMonFNALMARSFile_source.cc
gaini
       Analyses/src/ReadCaloDigi_module.cc
       Trigger/src/ReadTriggerInfo_module.cc
pasha
       CalPatRec/src/DeltaFinder2Diag_tool.cc
       CalPatRec/src/DeltaFinderAna_module.cc
       CalPatRec/src/DeltaFinderDiag_tool.cc
ralf
       Analyses/src/CosmicAnalysis_module.cc
       CRVAnalysis/src/CRVAnalysis.cc
       EventDisplay/src/TrackColorSelector.cc

rob    Analyses/src/CORSIKAGenPlots_module.cc
       Analyses/src/CRYGenPlots_module.cc
       Analyses/src/GeomVis_module.cc
       Analyses/src/PbarAnalysis2_module.cc
       EventGenerator/src/AntiProtonGun_module.cc
       Print/src/SimParticlePrinter.cc
       TrkDiag/src/BkgDiag_module.cc
       Validation/src/ValId.cc
       Validation/src/ValSimParticle.cc
       Validation/src/ValTrackSummary.cc
       TrkExt/src/TrkExtDiag.cc

sophie
       CosmicReco/src/CosmicMCRecoDiff_module.cc
       CosmicReco/src/CosmicTrackDiag_module.cc

**Comment by kutschke** [comment]
Oops - pasted this into the wrong PR.  Sorry for the noise.

**Comment by gianipez** [comment]
> @gianipez is there anyone who can meaningfully review these changes? Do you know if these changes will affect the nightly validation plots?

Hi Rob, these changes will not affect any nightly validation plots. I'm using this class in a tool for a module that a student from my group is developing and hopefully will commit in the coming month. 

I expect that in the coming months, other tools supporting other pattern-reco module will be "upgraded" and will start using this class as well. I think that only my group is/will-be using these tools, so I don't have a name to suggest to you.

**Comment by kutschke** [comment]
@FNALbuild run build test

**Pull request merged**
